//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Envy.rc
//
#define IDC_SEARCH_BOX                  110
#define IDC_FILTER_BOX                  112
#define IDC_MEDIA_POSITION              114
#define IDC_MEDIA_SPEED                 115
#define IDC_MEDIA_VOLUME                116
#define IDR_MAINFRAME                   120
#define IDR_HOMEFRAME                   121
#define IDR_DOWNLOADSFRAME              122
#define IDR_UPLOADSFRAME                123
#define IDR_LIBRARYFRAME                124
#define IDR_MEDIAFRAME                  125
#define IDR_IRCFRAME                    126
#define IDR_CHATFRAME                   127
#define IDR_CHANSFRAME                  128
#define IDR_USERSFRAME                  129
#define IDR_SEARCHFRAME                 130
#define IDR_SEARCHPADFRAME              131
#define IDR_SEARCHMONITORFRAME          132
#define IDR_HITMONITORFRAME             133
#define IDR_HOSTCACHEFRAME              134
#define IDR_BROWSEHOSTFRAME             135
#define IDR_NEIGHBOURSFRAME             136
#define IDR_DISCOVERYFRAME              137
#define IDR_SECURITYFRAME               138
#define IDR_SCHEDULERFRAME              139
#define IDR_SYSTEMFRAME                 140
#define IDR_TRAFFICFRAME                141
#define IDR_PACKETFRAME                 142
#define IDI_OPENTICK                    150
#define IDI_OPENTICK_HOVER              151
#define IDI_CLOSETICK                   152
#define IDI_CLOSETICK_HOVER             153
#define IDI_POINTER_ARROW_IN            154
#define IDI_POINTER_ARROW_OUT           155
#define IDI_UPDOWN_ARROW                156
#define IDI_FOLDER_CLOSED               157
#define IDI_FOLDER_OPEN                 158
#define IDI_BROWSE                      159
#define IDI_CHECKMARK                   160
#define IDI_CHEVRON                     161
#define IDI_COLLECTION                  162
#define IDI_COLLECTION_MASK             163
#define IDI_COLORS                      164
#define IDI_COMMERCIAL                  165
#define IDI_COMPUTER                    170
#define IDI_DISCOVERY_BLUE              172
#define IDI_DISCOVERY_GRAY              173
#define IDI_DOWNLOAD_MONITOR            174
#define IDI_EXECUTABLE                  175
#define IDI_FILE                        176
#define IDI_FAKE                        177
#define IDI_BUSY                        178
#define IDI_FIREWALLED                  180
#define IDI_FLAG_ENGLISH                181
#define IDI_HELP                        182
#define IDI_HASH                        183
#define IDI_LOCKED                      184
#define IDI_NOTASK                      185
#define IDI_MULTIFILE                   186
#define IDI_PARTIAL                     188
#define IDI_PREVIEW                     189
#define IDI_PROPERTIES                  190
#define IDI_RATING_GOOD                 191
#define IDI_RATING_AVERAGE              192
#define IDI_RATING_FAKE                 193
#define IDI_SEARCH_FOLDER               195
#define IDI_SKIN                        196
#define IDI_STAR                        197
#define IDI_TICK                        198
#define IDI_UNSTABLE                    199
#define IDI_WIZARD_DOT                  200
#define IDI_WEB_URL                     201
#define IDI_WORLD                       202
#define IDI_MAIL                        203
#define IDI_CONTACT_AOL                 204
#define IDI_CONTACT_ICQ                 205
#define IDI_CONTACT_SKYPE               206
#define IDI_CONTACT_YAHOO               207
#define IDI_CONTACT_GOOGLE              208
#define IDI_CONTACT_TWITTER             209
#define IDI_CONTACT_FACEBOOK            210
#define IDI_FAVICON                     212
#define IDI_INCOMING                    214
#define IDI_OUTGOING                    215
#define IDI_USER                        216
#define IDI_USER_ME                     218
#define IDI_SECURITY_ACCEPT             219
#define IDI_SECURITY_DENY               220
#define IDC_HAND                        280
#define IDR_COPY                        281
#define IDR_MOVE                        282
#define IDR_COPY_XP                     284
#define IDR_MOVE_XP                     285
#define IDB_MENUBAR                     300
#define IDB_REMOTE_SKIN                 301		// Hardcoded Default.xml
#define IDB_NAVBAR_IMAGE                302		// Hardcoded Default.xml
#define IDB_NAVBAR_IMAGE_RTL            303
#define IDB_NAVBAR_ALPHA                304		// Hardcoded Default.xml
#define IDB_NAVBAR_ALPHA_RTL            305
#define IDB_PROTOCOLS                   306
#define IDB_IRCICONS                    307
#define IDB_SOCIAL                      308
#define IDB_CHILDFRAME                  309
#define IDB_BANNER                      310		// Hardcoded Default.xml
#define IDB_BANNER_MARK                 312
#define IDB_BOX_MARK                    313
#define IDB_PANEL_MARK                  314
#define IDB_SMALL_STAR                  316
#define IDB_COLORDOT                    317
#define IDB_FONT_SYMBOLS                318
#define IDB_MEDIA_STATES                320
#define IDB_SORT_ASC                    321
#define IDB_SORT_DESC                   322
#define IDB_TASKBOX_CAPTION             324
#define IDB_TASKPANEL_FOOTER            325
#define IDB_MUSICBRAINZ_LOGO            326
#define IDR_LOGO                        328
#define IDR_LARGE_LOGO                  330		// Hardcoded Default.xml
#define IDR_HOME_HEADER                 332		// Hardcoded Default.xml
#define IDR_HOME_HEADER_REPEAT          333		// Hardcoded Default.xml
#define IDR_QRCODE                      334
#define IDR_XML_DEFAULT                 350
#define IDR_XML_DEFINITIONS             351
#define IDR_XML_SCHEMA_MAPS             352
#define IDR_HTML_ABOUT                  360
#define IDR_HTML_BUSY                   361
#define IDR_HTML_BADRANGE               362
#define IDR_HTML_BROWSER                363
#define IDR_HTML_DISABLED               364
#define IDR_HTML_FILENOTFOUND           365
#define IDR_HTML_HASHMISMATCH           366
#define IDD_SETTINGS_GENERAL            500
#define IDD_SETTINGS_LIBRARY            501
#define IDD_SETTINGS_MEDIA              502
#define IDD_SETTINGS_IRC                503
#define IDD_SETTINGS_COMMUNITY          504
#define IDD_SETTINGS_REMOTE             505
#define IDD_SETTINGS_WEB                506
#define IDD_SETTINGS_RICH               507
#define IDD_SETTINGS_CONNECTION         508
#define IDD_SETTINGS_DOWNLOADS          509
#define IDD_SETTINGS_UPLOADS            510
#define IDD_SETTINGS_NETWORKS           511
#define IDD_SETTINGS_GNUTELLA           512
#define IDD_SETTINGS_DONKEY             513
#define IDD_SETTINGS_DC                 514
#define IDD_SETTINGS_BITTORRENT         515
#define IDD_SETTINGS_SKINS              516
#define IDD_SETTINGS_PLUGINS            517
#define IDD_SETTINGS_ADVANCED           518
#define IDD_SETTINGS_PROTOCOLS          519
#define IDD_WIZARD_WELCOME              520
#define IDD_WIZARD_CONNECTION           521
#define IDD_WIZARD_NETWORKS             522
#define IDD_WIZARD_FOLDERS              523
#define IDD_WIZARD_SHARING              524
#define IDD_WIZARD_INTERFACE            525
#define IDD_WIZARD_PROFILE              526
#define IDD_WIZARD_FINISHED             527
#define IDD_PROFILE_PROFILE             530
#define IDD_PROFILE_AVATAR              531
#define IDD_PROFILE_BIO                 532
#define IDD_PROFILE_CONTACT             533
#define IDD_PROFILE_FILES               534
#define IDD_PROFILE_FAVORITES           535
#define IDD_PROFILE_IDENTITY            536
#define IDD_PROFILE_CERTIFICATE         538
#define IDD_DEBUG_HEX                   539
#define IDD_FILE_GENERAL                540
#define IDD_FILE_COMMENTS               541
#define IDD_FILE_METADATA               542
#define IDD_FILE_SHARING                543
#define IDD_TORRENT_FILES               544
#define IDD_TORRENT_TRACKERS            545
#define IDD_TORRENT_GENERAL             546
#define IDD_DOWNLOAD_EDIT               548
#define IDD_DOWNLOAD_ACTIONS            549
#define IDD_ABOUT                       600
#define IDD_HELP                        601
#define IDD_SPLASH                      602
#define IDD_LANGUAGE                    603
#define IDD_PROGRESSBAR                 604
#define IDD_MESSAGE                     605
#define IDD_PROMOTE                     606
#define IDD_WARNINGS                    608
#define IDD_DOWNLOAD                    610
#define IDD_DOWNLOAD_GROUP              612
#define IDD_DOWNLOAD_MONITOR            614
#define IDD_DOWNLOAD_REVIEWS            615
#define IDD_FILE_COPY                   616
#define IDD_FILE_PREVIEW                617
#define IDD_FILE_SOURCES                618
#define IDD_DELETE_FILE                 620
#define IDD_EXISTING_FILE               621
#define IDD_COLLECTION_EXPORT           622
#define IDD_DISCOVERY_SERVICE           623
#define IDD_DONKEY_IMPORT               624
#define IDD_UPDATE_SERVERS              625
#define IDD_TORRENT_SEED                626
#define IDD_CONNECT_TO                  627
#define IDD_FILTER_SAVE_AS              628
#define IDD_FILTER_SEARCH               629
#define IDD_FOLDER_PROPERTIES           630
#define IDD_FOLDER_SCAN                 631
#define IDD_GRAPH_ITEM                  632
#define IDD_GRAPH_LIST                  633
#define IDD_IRC_INPUTBOX                634
#define IDD_MEDIA_VIS                   635
#define IDD_NEW_SEARCH                  636
#define IDD_PLUGIN_EXT_SETUP            638
#define IDD_BITPRINTS_DOWNLOAD          639
#define IDD_CLOSE_MODE                  640
#define IDD_CODEPAGES                   641
#define IDD_QUEUE_PROPERTIES            642
#define IDD_SCHEMA_COLUMNS              643
#define IDD_SCHEDULE_TASK               644
#define IDD_SECURE_RULE                 645
#define IDD_SHARE_MANAGER               646
#define IDD_SELECT                      648
#define IDD_UPGRADE                     649
#define IDD_URL_ACTION                  650
#define IDD_URL_COPY                    651
#define IDD_URL_EXPORT                  652
#define IDC_BANNER                      1001
#define IDC_ACTION_0                    1002
#define IDC_ACTION_1                    1003
#define IDC_ACTION_2                    1004
#define IDC_ADDRESS                     1005
#define IDC_AGENT                       1006
#define IDC_AGENT_ADD                   1007
#define IDC_AGENT_LIST                  1008
#define IDC_AGENT_REMOVE                1009
#define IDC_ALWAYS_OPEN                 1010
#define IDC_ANTIVIRUS                   1011
#define IDC_APPLY_METADATA              1012
#define IDC_ASSOCIATIONS                1013
#define IDC_AUTO_CONNECT                1014
#define IDC_AUTO_START                  1015
#define IDC_AVATAR_BROWSE               1016
#define IDC_AVATAR_REMOVE               1017
#define IDC_ADULT_FILTER                1018
#define IDC_BROWSE_FILES                1020
#define IDC_BROWSE_USER                 1021
#define IDC_BANDWIDTH_POINTS            1022
#define IDC_BANDWIDTH_SLIDER            1023
#define IDC_BANDWIDTH_VALUE             1024
#define IDC_CANCEL_DOWNLOAD             1026
#define IDC_CAN_ACCEPT                  1027
#define IDC_CAPACITY                    1028
#define IDC_CAPACITY_SPIN               1029
#define IDC_CAPTION                     1030
#define IDC_CHAT_ALLNETWORKS            1031
#define IDC_CHAT_ENABLE                 1032
#define IDC_CHAT_CENSOR                 1033
#define IDC_CHAT_FILTER                 1034
#define IDC_CLEAR_DOWNLOADS             1035
#define IDC_CLEAR_UPLOADS               1036
#define IDC_CLOSE                       1040
#define IDC_CLOSE_0                     1041
#define IDC_CLOSE_1                     1042
#define IDC_CLOSE_2                     1043
#define IDC_CLOSE_MODE                  1044
#define IDC_CODEPAGES                   1045
#define IDC_COLUMNS                     1046
#define IDC_COLLECTIONS_BROWSE          1047
#define IDC_COLLECTIONS_FOLDER          1048
#define IDC_COMPLETE_AND_VERIFY         1049
#define IDC_CONNECTION_PROGRESS         1050
#define IDC_CONNECTION_STATUS           1051
#define IDC_CONNECTION_TYPE             1052
#define IDC_CONNECT_ADVANCED            1053
#define IDC_CONNECT_HOST                1054
#define IDC_CONNECT_PORT                1055
#define IDC_CONNECT_PROMPT              1056
#define IDC_CONNECT_PROTOCOL            1057
#define IDC_CONNECT_ULTRAPEER           1058
#define IDC_COPY                        1060
#define IDC_COPYRIGHT                   1061
#define IDC_CREATE_GHOST                1062
#define IDC_DC_ENABLE                   1064
#define IDC_DC_SETUP                    1065
#define IDC_DEFAULT_VALUE               1066
#define IDC_DEFLATE_HUB2HUB             1067
#define IDC_DEFLATE_HUB2LEAF            1068
#define IDC_DEFLATE_LEAF2HUB            1069
#define IDC_DELETE_ALL                  1070
#define IDC_DELETE_FILTER               1071
#define IDC_DELETE_OPTIONS              1072
#define IDC_DESCRIPTION                 1073
#define IDC_DESCRIPTION_BASIC           1074
#define IDC_DESCRIPTION_EXPERT          1075
#define IDC_DISCOVERY_GO                1076
#define IDC_DISKNAME                    1077
#define IDC_DONT_CHECK                  1078
#define IDC_DOWNLOAD                    1080
#define IDC_DOWNLOADS_BROWSE            1081
#define IDC_DOWNLOADS_DEFAULT           1082
#define IDC_DOWNLOADS_FOLDER            1083
#define IDC_DOWNLOADS_QUEUE_LIMIT       1084
#define IDC_DOWNLOADS_BANDWIDTH_LIMIT   1085
#define IDC_DOWNLOADS_SIMPLEBAR         1086
#define IDC_ED2K_ENABLE                 1087
#define IDC_ED2K_SETUP                  1088
#define IDC_EDIT_PROFILE                1089
#define IDC_ENABLE                      1090
#define IDC_ENABLE_ALWAYS               1091
#define IDC_ENABLE_DHT                  1092
#define IDC_ENABLE_UPNP                 1093
#define IDC_ERASE                       1094
#define IDC_ERASE_FROM                  1095
#define IDC_ERASE_TO                    1096
#define IDC_EXPAND_DOWNLOAD             1097
#define IDC_EXPAND_MATCHES              1098
#define IDC_EXPIRE_D                    1100
#define IDC_EXPIRE_H                    1101
#define IDC_EXPIRE_M                    1102
#define IDC_EXT_ADD                     1103
#define IDC_EXT_LIST                    1104
#define IDC_EXT_REMOVE                  1105
#define IDC_FAIRUSE_MODE                1106
#define IDC_FONT                        1107
#define IDC_FOLDER                      1108
#define IDC_FILES                       1110
#define IDC_FILESIZE                    1111
#define IDC_FILE_SHA1                   1112
#define IDC_FILE_TIGER                  1113
#define IDC_FILE_ED2K                   1114
#define IDC_FILE_MD5                    1115
#define IDC_FILE_MODIFIED               1116
#define IDC_FILE_COMMENTS               1117
#define IDC_FILE_ICON                   1118
#define IDC_FILE_INDEX                  1119
#define IDC_FILE_NAME                   1120
#define IDC_FILE_PATH                   1121
#define IDC_FILE_SIZE                   1122
#define IDC_FILE_SHARE                  1123
#define IDC_FILE_SOURCE                 1124
#define IDC_FILE_SOURCES                1125
#define IDC_FILE_RATING                 1126
#define IDC_FILE_TAGS                   1127
#define IDC_FILE_TYPE                   1128
#define IDC_FILE_URN                    1129
#define IDC_FILE_LIST                   1130
#define IDC_FILE_HASH_LABEL             1131
#define IDC_FILTER                      1132
#define IDC_FILTERS                     1134
#define IDC_FILTER_ADD                  1135
#define IDC_FILTER_BUSY                 1136
#define IDC_FILTER_BOGUS                1138
#define IDC_FILTER_DRM                  1139
#define IDC_FILTER_LIST                 1140
#define IDC_FILTER_LOCAL                1141
#define IDC_FILTER_PUSH                 1142
#define IDC_FILTER_REJECT               1143
#define IDC_FILTER_REMOVE               1144
#define IDC_FILTER_RESTRICTED           1145
#define IDC_FILTER_SUSPECT              1146
#define IDC_FILTER_UNSTABLE             1147
#define IDC_FORGET_SOURCES              1148
#define IDC_FORGET_VERIFY               1149
#define IDC_G1_ENABLE                   1150
#define IDC_G1_ALWAYS                   1151
#define IDC_G1_CLIENTMODE               1152
#define IDC_G1_HUBS                     1153
#define IDC_G1_HUBS_SPIN                1154
#define IDC_G1_LEAFS                    1155
#define IDC_G1_LEAFS_SPIN               1156
#define IDC_G1_PEERS                    1157
#define IDC_G1_PEERS_SPIN               1158
#define IDC_G1_SETUP                    1159
#define IDC_G2_ENABLE                   1160
#define IDC_G2_ALWAYS                   1161
#define IDC_G2_CLIENTMODE               1162
#define IDC_G2_HUBS                     1163
#define IDC_G2_HUBS_SPIN                1164
#define IDC_G2_LEAFS                    1165
#define IDC_G2_LEAFS_SPIN               1166
#define IDC_G2_PEERS                    1167
#define IDC_G2_PEERS_SPIN               1168
#define IDC_G2_SETUP                    1169
#define IDC_GEOIP                       1170
#define IDC_GHOST_RATING                1172
#define IDC_GRAPH_ADD                   1180
#define IDC_GRAPH_EDIT                  1181
#define IDC_GRAPH_AXIS                  1182
#define IDC_GRAPH_COLOR                 1183
#define IDC_GRAPH_COLOR_BOX             1184
#define IDC_GRAPH_GRID                  1186
#define IDC_GRAPH_ITEMS                 1187
#define IDC_GRAPH_LEGEND                1188
#define IDC_GRAPH_PARAM                 1189
#define IDC_GRAPH_REMOVE                1190
#define IDC_GRAPH_SOURCE                1191
#define IDC_GRAPH_SPEED                 1192
#define IDC_GRAPH_SPEED_SPIN            1193
#define IDC_GRAPH_UNITS                 1194
#define IDC_GROUP_NETWORK               1195
#define IDC_GROUP_CONTENT               1196
#define IDC_GROUP_EXTERNAL              1197
#define IDC_GUID                        1200
#define IDC_GUID_BT                     1201
#define IDC_GUID_CREATE                 1202
#define IDC_HASH_INTEGRITY              1203
#define IDC_HASH_PRIORITY               1204
#define IDC_HASH_WINDOW                 1205
#define IDC_HIDE_SEARCH                 1206
#define IDC_HIGHLIGHT_NEW               1207
#define IDC_HUB_UNSHARE                 1208
#define IDC_IGNORE_LOCAL                1209
#define IDC_IMPORT                      1210
#define IDC_INBOUND_BIND                1212
#define IDC_INBOUND_HOST                1213
#define IDC_INBOUND_PORT                1214
#define IDC_INBOUND_RANDOM              1215
#define IDC_INBOUND_SPEED               1216
#define IDC_INCLUDE_SELF                1218
#define IDC_INCOMPLETE_BROWSE           1220
#define IDC_INCOMPLETE_FOLDER           1221
#define IDC_INFO_ICON                   1222
#define IDC_INFO_BUTTON1                1224
#define IDC_INFO_BUTTON2                1225
#define IDC_INFO_BUTTON3                1226
#define IDC_INFO_REMEMBER               1227
#define IDC_INFO_SPLIT                  1228
#define IDC_INFO_TEXT                   1229
#define IDC_INTEREST_ADD                1230
#define IDC_INTEREST_ALL                1231
#define IDC_INTEREST_LIST               1232
#define IDC_INTEREST_REMOVE             1233
#define IDC_INTERFACE_BASIC             1234
#define IDC_INTERFACE_EXPERT            1235
#define IDC_IRC_ALTERNATE               1240
#define IDC_IRC_COLOR_ACTION            1241
#define IDC_IRC_COLOR_BG                1242
#define IDC_IRC_COLOR_NOTICE            1243
#define IDC_IRC_COLOR_SERVER            1244
#define IDC_IRC_COLOR_TEXT              1245
#define IDC_IRC_COLOR_TEXTLOCAL         1246
#define IDC_IRC_COLOR_TOPIC             1247
#define IDC_IRC_COLOR_USERACTION        1248
#define IDC_IRC_FLOODENABLE             1250
#define IDC_IRC_FLOODLIMIT              1251
#define IDC_IRC_FLOODLIMIT_SPIN         1252
#define IDC_IRC_FONTSIZE                1253
#define IDC_IRC_FONTSIZE_SPIN           1254
#define IDC_IRC_ONCONNECT               1255
#define IDC_IRC_PROMPT                  1256
#define IDC_IRC_INPUT                   1258
#define IDC_IRC_NICK                    1260
#define IDC_IRC_REALNAME                1261
#define IDC_IRC_USERNAME                1262
#define IDC_IRC_SERVERNAME              1264
#define IDC_IRC_SERVERPORT              1265
#define IDC_IRC_SHOW                    1266
#define IDC_IRC_TEXTFONT                1268
#define IDC_IRC_TIMESTAMP               1269
#define IDC_LINKS                       1271
#define IDC_LINKS_SPIN                  1272
#define IDC_LABEL_ACTION                1274
#define IDC_LABEL_EVENT                 1275
#define IDC_LABEL_SUB_ACTION            1276
#define IDC_LEARN_ED2K_SERVERS          1277
#define IDC_LOC_CITY                    1280
#define IDC_LOC_COUNTRY                 1281
#define IDC_LOC_LAT                     1282
#define IDC_LOC_LONG                    1284
#define IDC_LOGO                        1299
#define IDC_LOG                         1300
#define IDC_IP_1                        1301
#define IDC_IP_2                        1302
#define IDC_IP_3                        1303
#define IDC_IP_4                        1304
#define IDC_MASK_1                      1305
#define IDC_MASK_2                      1306
#define IDC_MASK_3                      1307
#define IDC_MASK_4                      1308
#define IDC_MAKE_GHOSTS                 1310
#define IDC_MARKED_CHECK                1311
#define IDC_MARKED_LIST                 1312
#define IDC_MATCH_CHECK                 1313
#define IDC_MATCH_TEXT                  1314
#define IDC_MAXIMUM_CHECK               1315
#define IDC_MAXIMUM_VALUE               1316
#define IDC_MAX_FILES                   1320
#define IDC_MAX_FILES_SPIN              1321
#define IDC_MAX_HOST                    1322
#define IDC_MAX_HOST_SPIN               1323
#define IDC_MAX_SIZE                    1330
#define IDC_MAX_TPF                     1332
#define IDC_MAX_TPF_SPIN                1333
#define IDC_MAX_TRANSFERS               1334
#define IDC_MAX_TRANSFERS_SPIN          1335
#define IDC_MERGE_AND_VERIFY            1340
#define IDC_MEDIA_ADD                   1341
#define IDC_MEDIA_REMOVE                1342
#define IDC_MEDIA_PLAY                  1344
#define IDC_MEDIA_ENQUEUE               1345
#define IDC_MEDIA_SERVICE               1346
#define IDC_MEDIA_TYPES                 1348
#define IDC_MEDIA_VIS                   1349
#define IDC_MESSAGE                     1350
#define IDC_MESSAGE_1                   1351
#define IDC_MESSAGE_2                   1352
#define IDC_MESSAGE_3                   1353
#define IDC_MESSAGE_4                   1354
#define IDC_MESSAGE_COPY                1355
#define IDC_MESSAGE_MOVE                1356
#define IDC_MESSAGE_AVAILABLE           1357
#define IDC_MESSAGE_DELETED             1358
#define IDC_MESSAGE_DUPLICATES          1359
#define IDC_METHOD1                     1360
#define IDC_METHOD2                     1361
#define IDC_MIN_SIZE                    1362
#define IDC_MINIMUM_CHECK               1363
#define IDC_MINIMUM_VALUE               1364
#define IDC_MONITOR_ACTION              1365
#define IDC_MONITOR_AUTOCLOSE           1366
#define IDC_MONITOR_CLOSE               1368
#define IDC_MONITOR_FILE                1370
#define IDC_MONITOR_GRAPH               1371
#define IDC_MONITOR_ICON                1372
#define IDC_MONITOR_SHOW                1373
#define IDC_MONITOR_SOURCES             1374
#define IDC_MONITOR_SPEED               1375
#define IDC_MONITOR_STATUS              1376
#define IDC_MONITOR_TIME                1377
#define IDC_MONITOR_VOLUME              1378
#define IDC_NAME                        1380
#define IDC_NEW_WINDOW                  1382
#define IDC_OUTBOUND_HOST               1383
#define IDC_OUTBOUND_SPEED              1384
#define IDC_PLACEHOLDER                 1385
#define IDC_PLUGINS                     1386
#define IDC_PLUGINS_SETUP               1387
#define IDC_PLUGINS_WEB                 1388
#define IDC_PREVIEW                     1390
#define IDC_PREVIEW1                    1391
#define IDC_PREVIEW2                    1392
#define IDC_PREVIEW_STATUS              1394
#define IDC_PRIVATE_ADD                 1395
#define IDC_PRIVATE_REMOVE              1396
#define IDC_PRIVATE_TYPES               1398
#define IDC_PROFILE_NICK                1400
#define IDC_PROFILE_FIRST               1401
#define IDC_PROFILE_LAST                1402
#define IDC_PROFILE_GENDER              1403
#define IDC_PROFILE_AGE                 1404
#define IDC_PROFILE_BIO                 1405
#define IDC_PROFILE_EDIT                1406
#define IDC_PROFILE_EMAIL               1408
#define IDC_PROFILE_AOL                 1410
#define IDC_PROFILE_ICQ                 1411
#define IDC_PROFILE_SKYPE               1412
#define IDC_PROFILE_YAHOO               1414
#define IDC_PROFILE_JABBER              1415
#define IDC_PROFILE_TWITTER             1416
#define IDC_PROFILE_FACEBOOK            1417
#define IDC_PROFILE_GETENVY             1418
#define IDC_PROPERTIES                  1420
#define IDC_PROGRESS                    1421
#define IDC_PROGRESS_FILE               1422
#define IDC_PROGRESS_EVENT              1424
#define IDC_PROGRESS_SUB_EVENT          1425
#define IDC_PROTOCOLS                   1426
#define IDC_PROTOCOLS_CHECK             1427
#define IDC_PROTOCOLS_LIST              1428
#define IDC_PROMPT_URLS                 1430
#define IDC_QUEUES                      1432
#define IDC_QUEUE_NEW                   1434
#define IDC_QUEUE_DELETE                1435
#define IDC_QUEUE_EDIT                  1436
#define IDC_QUEUE_BOTH                  1437
#define IDC_QUEUE_LIBRARYONLY           1438
#define IDC_QUEUE_PARTIALONLY           1439
#define IDC_RATE_COMMENTS               1444
#define IDC_RATE_PROMPT                 1445
#define IDC_RATES_IN_BYTES              1446
#define IDC_REGEXP                      1450
#define IDC_RECENT_CLEAR                1451
#define IDC_RECENT_CLEAR_GHOSTS         1452
#define IDC_RECENT_DAYS                 1454
#define IDC_RECENT_DAYS_SPIN            1455
#define IDC_RECENT_TOTAL                1456
#define IDC_RECENT_TOTAL_SPIN           1457
#define IDC_REMOTE_ENABLE               1460
#define IDC_REMOTE_URL                  1461
#define IDC_REMOTE_USERNAME             1462
#define IDC_REMOTE_PASSWORD             1463
#define IDC_REMOTE_QRCODE               1464
#define IDC_REQUIRE_CONNECT             1465
#define IDC_RESPECT                     1466
#define IDC_REVIEWS                     1468
#define IDC_REVIEW_FILENAME             1469
#define IDC_REWARD_ENABLE               1470
#define IDC_ROTATE_ENABLE               1471
#define IDC_ROTATE_TIME                 1472
#define IDC_ROTATE_TIME_SPIN            1473
#define IDC_RESULTS                     1474
#define IDC_RESULTS_SPIN                1475
#define IDC_RULE_ACTION                 1476
#define IDC_RULE_COMMENT                1477
#define IDC_RULE_CONTENT                1478
#define IDC_RULE_EXPIRE                 1479
#define IDC_RULE_MATCH_ALL              1480
#define IDC_RULE_MATCH_ANY              1481
#define IDC_RULE_TYPE                   1482
#define IDC_SAFE_ADD                    1484
#define IDC_SAFE_REMOVE                 1485
#define IDC_SAFE_TYPES                  1486
#define IDC_SAVE                        1488
#define IDC_SAVE_FILTER                 1489
#define IDC_SCAN_FILE                   1490
#define IDC_SCAN_FILES                  1491
#define IDC_SCAN_VOLUME                 1492
#define IDC_SCHEMAS                     1494
#define IDC_SCHEMA_TYPES                1495
#define IDC_SET_DEFAULT_FILTER          1496
#define IDC_SERVICE_TYPE                1498
#define IDC_SERVER_WALK                 1499
#define IDC_SEARCH                      1500
#define IDC_SEARCH_START                1501
#define IDC_SEARCH_STOP                 1502
#define IDC_SEARCH_ADVANCED             1504
#define IDC_SEARCH_TEXT                 1505
#define IDC_SHARE_ADD                   1510
#define IDC_SHARE_REMOVE                1512
#define IDC_SHARE_FOLDERS               1514
#define IDC_SHARE_PARTIALS              1515
#define IDC_SHARE_PREVIEW               1516
#define IDC_SHARE_PREVIEW_DYNAMIC       1517
#define IDC_SHARE_OVERRIDE_0            1518
#define IDC_SHARE_OVERRIDE_1            1519
#define IDC_SHOW_SYSTEM                 1520
#define IDC_SEED                        1521
#define IDC_SKINS                       1522
#define IDC_SKINS_BROWSE                1523
#define IDC_SKINS_DELETE                1524
#define IDC_SKIN_NAME                   1526
#define IDC_SKIN_AUTHOR                 1527
#define IDC_SKIN_DESC                   1528
#define IDC_SKINS_WEB                   1529
#define IDC_SOURCES                     1530
#define IDC_SOURCES_SPIN                1531
#define IDC_SOURCE_MESH                 1532
#define IDC_SOURCE_NEW                  1533
#define IDC_SOURCE_ADD                  1534
#define IDC_SOURCE_REMOVE               1535
#define IDC_STATIC_NAME                 1536
#define IDC_STATIC_AUTHOR               1537
#define IDC_STATIC_DESC                 1538
#define IDC_STATIC_GROUPBOX             1540
#define IDC_SUB_EVENT                   1542
#define IDC_SMART_SERIES_DETECTION      1544
#define IDC_SWITCH_TO_TRANSFERS         1545
#define IDC_TEMPLATES                   1550
#define IDC_TEMPLATES_DELETE            1551
#define IDC_TEMPLATES_EXPLAIN           1552
#define IDC_TEMPLATE_AUTHOR             1553
#define IDC_TEMPLATE_DESC               1554
#define IDC_TEMPLATE_NAME               1555
#define IDC_THROTTLE_MODE               1556
#define IDC_TIMEOUT_CONNECTION          1560
#define IDC_TIMEOUT_CONNECTION_SPIN     1561
#define IDC_TIMEOUT_HANDSHAKE           1562
#define IDC_TIMEOUT_HANDSHAKE_SPIN      1563
#define IDC_TIP_ALPHA                   1564
#define IDC_TIP_DELAY                   1565
#define IDC_TIP_DELAY_SPIN              1566
#define IDC_TIP_DISPLAY                 1567
#define IDC_TIP_SHADOW                  1568
#define IDC_TITLE                       1570
#define IDC_TORRENTS_BROWSE             1600
#define IDC_TORRENTS_FOLDER             1601
#define IDC_TORRENTS_TORRENTMAKER       1602
#define IDC_TORRENTS_TORRENTMAKERBROWSE 1604
#define IDC_TORRENT_AUTOCLEAR           1605
#define IDC_TORRENT_CLEAR_PERCENTAGE    1606
#define IDC_TORRENT_CLEAR_SPIN          1607
#define IDC_TORRENT_CLIENTLINKS         1608
#define IDC_TORRENT_COUNT               1609
#define IDC_TORRENT_COMMENTS            1610
#define IDC_TORRENT_COMPLETED           1612
#define IDC_TORRENT_CREATEDBY           1614
#define IDC_TORRENT_CREATIONDATE        1615
#define IDC_TORRENT_DEFAULTTRACKER      1616
#define IDC_TORRENT_ENDGAME             1617
#define IDC_TORRENT_DOWNLOADS           1618
#define IDC_TORRENT_DOWNLOADS_SPIN      1619
#define IDC_TORRENT_NAME                1620
#define IDC_TORRENT_FILE                1621
#define IDC_TORRENT_FILES               1622
#define IDC_TORRENT_INCOMPLETE          1623
#define IDC_TORRENT_INTERFACE           1624
#define IDC_TORRENT_LINKS_SPIN          1625
#define IDC_TORRENT_OTHER               1626
#define IDC_TORRENT_PREFERENCE          1627
#define IDC_TORRENT_STARTDOWNLOADS      1628
#define IDC_TORRENT_REFRESH             1629
#define IDC_TORRENT_TRACKER             1630
#define IDC_TORRENT_TRACKERMODE         1631
#define IDC_TORRENT_TRACKERS            1632
#define IDC_TORRENT_UPLOADTOTAL         1634
#define IDC_TORRENT_VIEW                1635
#define IDC_TRANSFERS_MAX               1636
#define IDC_TRANSFERS_MAX_SPIN          1637
#define IDC_TRANSFERS_MIN               1638
#define IDC_TRANSFERS_MIN_SPIN          1639
#define IDC_TRAY_MINIMISE               1640
#define IDC_TRUST_SHA1                  1641
#define IDC_TRUST_TIGER                 1642
#define IDC_TRUST_ED2K                  1643
#define IDC_TRUST_MD5                   1644
#define IDC_TRUST_BTH                   1645
#define IDC_UPLOADS_BANDWIDTH_LIMIT     1650
#define IDC_UPDATE_CHECK                1651
#define IDC_URI_MAGNET                  1652
#define IDC_URI_GNUTELLA                1653
#define IDC_URI_ED2K                    1654
#define IDC_URI_PIOLET                  1655
#define IDC_URI_TORRENT                 1656
#define IDC_URI_DC                      1658
#define IDC_URL_DOWNLOAD                1660
#define IDC_URL_MAGNET                  1661
#define IDC_URL_ED2K                    1662
#define IDC_URL_HOST                    1663
#define IDC_URL_HASH                    1664
#define IDC_URL_FORMAT                  1665
#define IDC_URL_NAME_TITLE              1666
#define IDC_URL_NAME_VALUE              1667
#define IDC_URL_PRESET                  1668
#define IDC_URL_SEARCH                  1669
#define IDC_URL_TOKEN                   1670
#define IDC_URL_URN_TITLE               1671
#define IDC_URL_URN_VALUE               1672
#define IDC_URL                         1674
#define IDC_URN_SHA1                    1675
#define IDC_URN_TIGER                   1676
#define IDC_URN_ED2K                    1677
#define IDC_URN_MD5                     1678
#define IDC_URN_BTH                     1679
#define IDC_VALUE                       1680
#define IDC_VALUE_SPIN                  1681
#define IDC_VIS_SETUP                   1682
#define IDC_VIS_SIZE                    1683
#define IDC_VIRTUAL_FILES               1684
#define IDC_WATCH_FOLDERS               1685
#define IDC_WEB                         1686
#define IDC_WEB_ADD                     1687
#define IDC_WEB_REMOVE                  1688
#define IDC_WEB_HOOK                    1689
#define IDC_WEB_LIST                    1690
#define IDC_WEB_NAME                    1691
#define IDC_WEB_URL                     1692
#define IDC_WIZARD_AUTO                 1693
#define IDC_WIZARD_DOWNLOAD_SPEED       1694
#define IDC_WIZARD_UPLOAD_SPEED         1695
#define IDC_WIZARD_UPNP                 1696
#define IDC_WIZARD_PORT                 1697
#define IDC_WIZARD_RANDOM               1698
#define IDC_WIZARD_STARTUP              1699
#define IDC_EVENTTYPE                   1700
#define IDC_EVERYDAY                    1701
#define IDC_ONLYONCE                    1702
#define IDC_ACTIVE                      1703
#define IDC_DATE                        1704
#define IDC_TIME                        1705
#define IDC_STATIC_LIMITED_UP           1710
#define IDC_STATIC_LIMITED_DOWN         1711
#define IDC_SCHEDULER_LIMITED_UP        1712
#define IDC_SCHEDULER_LIMITED_DOWN      1713
#define IDC_SCHEDULER_LIMITED_SPIN_UP   1714
#define IDC_SCHEDULER_LIMITED_SPIN_DOWN 1715
#define IDC_SCHEDULER_LIMITED_NETWORKS  1716
#define IDC_BUTTON_ALLDAYS              1720
#define IDC_CHECK_MON                   1721
#define IDC_CHECK_TUES                  1722
#define IDC_CHECK_WED                   1723
#define IDC_CHECK_THU                   1724
#define IDC_CHECK_FRI                   1725
#define IDC_CHECK_SAT                   1726
#define IDC_CHECK_SUN                   1727
#define IDC_CHECK                       1728
#define IDC_EDIT_HEX                    1730
#define IDC_WIZARD_NOSKIN               1750
#define IDC_WIZARD_DEFAULTSKIN          1751
#define IDC_WIZARD_DARKSKIN             1752
#define IDC_STATIC_0                    1800
#define IDC_STATIC_1                    1801
#define IDC_STATIC_2                    1802
#define IDC_STATIC_3                    1803
#define IDC_STATIC_4                    1804
#define IDC_STATIC_5                    1805
#define IDC_STATIC_6                    1806
#define IDC_STATIC_7                    1807
#define IDC_STATIC_8                    1808
#define IDC_STATIC_9                    1809
#define IDS_ENVY                 20000
#define IDS_GENERAL_YES                 20001
#define IDS_GENERAL_NO                  20002
#define IDS_GENERAL_OK                  20003
#define IDS_GENERAL_CANCEL              20004
#define IDS_GENERAL_BACK                20005
#define IDS_GENERAL_NEXT                20006
#define IDS_GENERAL_CONTINUE            20007
#define IDS_GENERAL_CLOSE               20008
#define IDS_GENERAL_OF                  20009
#define IDS_GENERAL_ALL                 20010
#define IDS_GENERAL_AUTO                20011
#define IDS_GENERAL_CUSTOM              20012
#define IDS_GENERAL_DEFAULT             20013
#define IDS_GENERAL_FINISH              20014
#define IDS_GENERAL_IGNORE              20015
#define IDS_GENERAL_RETRY               20016
#define IDS_GENERAL_ABORT               20017
#define IDS_GENERAL_TRYAGAIN            20018
#define IDS_GENERAL_PLEASEWAIT          20019
#define IDS_FILE                        20020
#define IDS_FILES                       20021
#define IDS_FILES_ALL                   20022
#define IDS_FILES_NONE                  20023
#define IDS_FILES_LARGE                 20024
#define IDS_FILES_MEDIUM                20025
#define IDS_FILES_SMALL                 20026
#define IDS_FILES_PARTIAL               20027
#define IDS_FILES_LIBRARY               20028
#define IDS_FILES_TYPE                  20029
#define IDS_DAY_EVERYDAY                20050
#define IDS_DAY_MONDAY                  20051
#define IDS_DAY_TUESDAY                 20052
#define IDS_DAY_WEDNESDAY               20053
#define IDS_DAY_THURSDAY                20054
#define IDS_DAY_FRIDAY                  20055
#define IDS_DAY_SATURDAY                20056
#define IDS_DAY_SUNDAY                  20057
#define IDS_RATING_NONE                 20060
#define IDS_RATING_1                    20061
#define IDS_RATING_2                    20062
#define IDS_RATING_3                    20063
#define IDS_RATING_4                    20064
#define IDS_RATING_5                    20065
#define IDS_RATING_6                    20066
#define IDS_PRIORITY_OFF                20070
#define IDS_PRIORITY_LOW                20071
#define IDS_PRIORITY_NORMAL             20072
#define IDS_PRIORITY_HIGH               20074
#define IDS_BETA_EXPIRED                20080
#define IDS_BITPRINTS_CLOSE             20081
#define IDS_BITPRINTS_FINISHED          20082
#define IDS_BITPRINTS_REQUESTING        20083
#define IDS_BITPRINTS_SUCCESS           20084
#define IDS_BITPRINTS_NOT_HASHED        20086
#define IDS_BITPRINTS_MESSAGE           20088
#define IDS_BROWSE_CLOSED               20100
#define IDS_BROWSE_BAD_RESPONSE         20101
#define IDS_BROWSE_CANT_CONNECT         20102
#define IDS_BROWSE_CANT_CONNECT_TO      20103
#define IDS_BROWSE_CANT_PUSH_TO         20104
#define IDS_BROWSE_CONNECTING           20105
#define IDS_BROWSE_CONNECTING_TO        20106
#define IDS_BROWSE_DOWNLOADING          20107
#define IDS_BROWSE_DOWNLOADING_FROM     20108
#define IDS_BROWSE_DROPPED              20109
#define IDS_BROWSE_FINISHED             20110
#define IDS_BROWSE_INTRO_FORMAT         20111
#define IDS_BROWSE_HTTPCODE             20112
#define IDS_BROWSE_NOT_HTTP             20113
#define IDS_BROWSE_NOT_SUPPORTED        20114
#define IDS_BROWSE_PACKET_ERROR         20115
#define IDS_BROWSE_PUSHED               20116
#define IDS_BROWSE_PUSHED_TO            20117
#define IDS_BROWSE_REQUESTING           20118
#define IDS_BROWSE_SENT_REQUEST         20119
#define IDS_BROWSE_TIMEOUT              20120
#define IDS_BROWSE_TITLE_FORMAT         20121
#define IDS_BT_CLIENT_ONLINE            20122
#define IDS_BT_CLIENT_ACCEPTED          20123
#define IDS_BT_CLIENT_CONNECTING        20124
#define IDS_BT_CLIENT_CONNECT_TIMEOUT   20125
#define IDS_BT_CLIENT_DROP_CONNECTED    20126
#define IDS_BT_CLIENT_DROP_CONNECTING   20127
#define IDS_BT_CLIENT_DROP_HANDSHAKE    20128
#define IDS_BT_CLIENT_DUPLICATE         20129
#define IDS_BT_CLIENT_EXCHANGE          20130
#define IDS_BT_CLIENT_EXTENDED          20131
#define IDS_BT_CLIENT_HANDSHAKE_TIMEOUT 20132
#define IDS_BT_CLIENT_HANDSHAKING       20133
#define IDS_BT_CLIENT_MAX_CONNECTIONS   20134
#define IDS_BT_CLIENT_INACTIVE_FILE     20135
#define IDS_BT_CLIENT_UNKNOWN_FILE      20136
#define IDS_BT_CLIENT_WRONG_FILE        20137
#define IDS_BT_CLIENT_WRONG_GUID        20138
#define IDS_BT_CLIENT_LOST              20139
#define IDS_BT_ENCODING                 20140
#define IDS_BT_PRIVATE                  20141
#define IDS_BT_SEED_ALREADY             20142
#define IDS_BT_SEED_COPY_FAIL           20143
#define IDS_BT_SEED_CREATE_FAIL         20144
#define IDS_BT_SEED_ERROR               20145
#define IDS_BT_SEED_PARSE_ERROR         20146
#define IDS_BT_SEED_SOURCE_LOST         20147
#define IDS_BT_SEED_SOURCE_SIZE         20148
#define IDS_BT_SEED_VERIFY_FAIL         20149
#define IDS_BT_TRACKER_DOWN             20150
#define IDS_BT_TRACKER_MULTI            20151
#define IDS_BT_TRACKER_CHANGE           20152
#define IDS_BT_TRACKER_ERROR            20153
#define IDS_BT_TRACKER_PARSE_ERROR      20154
#define IDS_BT_TRACKER_SUCCESS          20155
#define IDS_BT_UPDATE_CONVERTING        20156
#define IDS_BT_UPDATE_TITLE             20157
#define IDS_BT_PREFETCH_ERROR           20158
#define IDS_BT_PREFETCH_FILE            20159
#define IDS_CHAT_ACCEPTED_X             20160
#define IDS_CHAT_CANT_CONNECT           20161
#define IDS_CHAT_CANT_PUSH              20162
#define IDS_CHAT_CLOSED                 20163
#define IDS_CHAT_CLOSED_X               20164
#define IDS_CHAT_CONNECTED              20165
#define IDS_CHAT_CONNECTED_X            20166
#define IDS_CHAT_CONNECTING_TO          20167
#define IDS_CHAT_CONNECTING_X           20168
#define IDS_CHAT_CONNECT_FAIL_X         20169
#define IDS_CHAT_DROPPED                20170
#define IDS_CHAT_DROPPED_X              20171
#define IDS_CHAT_HANDSHAKE_FAIL         20172
#define IDS_CHAT_HANDSHAKE_G1           20173
#define IDS_CHAT_HANDSHAKE_G2           20174
#define IDS_CHAT_NEED_PROFILE           20175
#define IDS_CHAT_NOT_CONNECTED_1        20176
#define IDS_CHAT_NOT_CONNECTED_2        20177
#define IDS_CHAT_NICK_X                 20178
#define IDS_CHAT_ONLINE_X               20179
#define IDS_CHAT_PRIORITY_GRANTED       20180
#define IDS_CHAT_PRIVATE_AWAY           20181
#define IDS_CHAT_PRIVATE_ONLINE         20182
#define IDS_CHAT_PRIVATE_REFUSED        20183
#define IDS_CHAT_PRIVATE_START          20184
#define IDS_CHAT_PROFILE_ACCEPTED       20185
#define IDS_CHAT_PUSH_DONE              20186
#define IDS_CHAT_PUSH_SENT              20187
#define IDS_CHAT_PROTOCOL_X             20188
#define IDS_CHAT_RESPONSE_X             20189
#define IDS_CHAT_UNCONNECTED_X          20190
#define IDS_CHAT_UNRECOGNISED_X         20191
#define IDS_CHAT_CAPTCHA_ACCEPTED       20192
#define IDS_CHAT_CAPTCHA_DENIED         20193
#define IDS_CHAT_CAPTCHA_REQUEST        20194
#define IDS_COLLECTION_WIZARD_NOCUSTOM  20196
#define IDS_COLLECTION_WIZARD_NOTVALID  20197
#define IDS_COPIED_TO_CLIPBOARD         20198
#define IDS_CLOSING_AFTER               20199
#define IDS_DOWNLOAD_ADDED              20200
#define IDS_DOWNLOAD_ALREADY            20201
#define IDS_DOWNLOAD_BAD_PUSH           20202
#define IDS_DOWNLOAD_BOOST              20203
#define IDS_DOWNLOAD_BUSY               20204
#define IDS_DOWNLOAD_DISK_SPACE         20205
#define IDS_DOWNLOAD_CANT_MOVE          20206
#define IDS_DOWNLOAD_CLEAR_GROUP        20207
#define IDS_DOWNLOAD_CLOSING_EXTRA      20208
#define IDS_DOWNLOAD_CLOSING_OVERFLOW   20209
#define IDS_DOWNLOAD_COMPLETED          20210
#define IDS_DOWNLOAD_CONFIRM_CLEAR      20211
#define IDS_DOWNLOAD_CONFIRM_CLEAR_PAUSED 20212
#define IDS_DOWNLOAD_CONFIRM_DELETE     20213
#define IDS_DOWNLOAD_CONNECTED          20214
#define IDS_DOWNLOAD_CONNECTING         20215
#define IDS_DOWNLOAD_CONNECT_ERROR      20216
#define IDS_DOWNLOAD_CONTENT            20217
#define IDS_DOWNLOAD_DISABLED           20218
#define IDS_DOWNLOAD_DROPPED            20219
#define IDS_DOWNLOAD_EDIT_ACTIVE_TASK   20220
#define IDS_DOWNLOAD_EDIT_BAD_RANGE     20221
#define IDS_DOWNLOAD_EDIT_BAD_HASH      20222
#define IDS_DOWNLOAD_EDIT_CHANGE_HASH   20223
#define IDS_DOWNLOAD_EDIT_CHANGE_NAME   20224
#define IDS_DOWNLOAD_EDIT_CHANGE_SIZE   20225
#define IDS_DOWNLOAD_EDIT_COMPLETE_NOHASH 20226
#define IDS_DOWNLOAD_EDIT_COMPLETE_VERIFY 20227
#define IDS_DOWNLOAD_EDIT_FORGET_VERIFY 20228
#define IDS_DOWNLOAD_EDIT_FORGET_SOURCES 20229
#define IDS_DOWNLOAD_EDIT_CANCEL_DOWNLOAD 20230
#define IDS_DOWNLOAD_EDIT_CANT_ERASE    20231
#define IDS_DOWNLOAD_EDIT_ERASED        20232
#define IDS_DOWNLOAD_FILENOTFOUND       20242
#define IDS_DOWNLOAD_FILE_CREATE        20243
#define IDS_DOWNLOAD_FILE_CREATE_ERROR  20244
#define IDS_DOWNLOAD_FILE_OPEN_ERROR    20245
#define IDS_DOWNLOAD_FRAGMENT_END       20246
#define IDS_DOWNLOAD_FRAGMENT_OVERLAP   20247
#define IDS_DOWNLOAD_FRAGMENT_REQUEST   20248
#define IDS_DOWNLOAD_DC_HUBLIST         20249
#define IDS_DOWNLOAD_GROUP              20250
#define IDS_DOWNLOAD_GROUP_DEFAULT      20251
#define IDS_DOWNLOAD_NEW_GROUP          20252
#define IDS_DOWNLOAD_HASHSET_CORRUPT    20253
#define IDS_DOWNLOAD_HASHSET_ERROR      20254
#define IDS_DOWNLOAD_HASHSET_READY      20255
#define IDS_DOWNLOAD_HASHSET_REQUEST    20256
#define IDS_DOWNLOAD_INFLATE_ERROR      20257
#define IDS_DOWNLOAD_METADATA_RECV      20258
#define IDS_DOWNLOAD_METADATA_REQUEST   20259
#define IDS_DOWNLOAD_PROPERTIES         20260
#define IDS_DOWNLOAD_HTTPCODE           20261
#define IDS_DOWNLOAD_NOHTTP             20262
#define IDS_DOWNLOAD_PUSHED             20263
#define IDS_DOWNLOAD_PUSH_SENT          20264
#define IDS_DOWNLOAD_QUEUED             20265
#define IDS_DOWNLOAD_QUEUE_DROP         20266
#define IDS_DOWNLOAD_QUEUE_HUGE         20267
#define IDS_DOWNLOAD_QUEUE_TIMEOUT      20268
#define IDS_DOWNLOAD_REQUEST_TIMEOUT    20269
#define IDS_DOWNLOAD_REMOVE             20270
#define IDS_DOWNLOAD_MOVED              20271
#define IDS_DOWNLOAD_PAUSED             20272
#define IDS_DOWNLOAD_RESUMED            20273
#define IDS_DOWNLOAD_SOURCES            20275
#define IDS_DOWNLOAD_SOURCES_CONNECTED  20276
#define IDS_DOWNLOAD_TIGER_CORRUPT      20280
#define IDS_DOWNLOAD_TIGER_MISMATCH     20281
#define IDS_DOWNLOAD_TIGER_RANGE        20282
#define IDS_DOWNLOAD_TIGER_READY        20283
#define IDS_DOWNLOAD_TIGER_RECV         20284
#define IDS_DOWNLOAD_TIGER_REQUEST      20285
#define IDS_DOWNLOAD_TRAFFIC_TIMEOUT    20286
#define IDS_DOWNLOAD_USEFUL_RANGE       20290
#define IDS_DOWNLOAD_UNKNOWN_PUSH       20291
#define IDS_DOWNLOAD_VERIFY_DROP        20292
#define IDS_DOWNLOAD_VERIFY_FAIL        20293
#define IDS_DOWNLOAD_VERIFY_SUCCESS     20294
#define IDS_DOWNLOAD_WRONG_HASH         20295
#define IDS_DOWNLOAD_WRONG_RANGE        20296
#define IDS_DOWNLOAD_WRONG_SIZE         20297
#define IDS_DOWNLOAD_416_WITHOUT_RANGE  20298
#define IDS_CONNECTION_ACCEPTED         20300
#define IDS_CONNECTION_ALREADY_ABORT    20301
#define IDS_CONNECTION_ALREADY_REFUSE   20302
#define IDS_CONNECTION_ATTEMPTING       20303
#define IDS_CONNECTION_BYE              20304
#define IDS_CONNECTION_CLOSED           20305
#define IDS_CONNECTION_CONNECTED        20306
#define IDS_CONNECTION_CONNECT_FAIL     20307
#define IDS_CONNECTION_DROPPED          20308
#define IDS_CONNECTION_PEERPRUNE        20309
#define IDS_CONNECTION_REFUSED          20310
#define IDS_CONNECTION_TIMEOUT_CONNECT  20311
#define IDS_CONNECTION_TIMEOUT_TRAFFIC  20312
#define IDS_DISCOVERY_BOOTSTRAP         20313
#define IDS_DISCOVERY_FAILED            20314
#define IDS_DISCOVERY_FAIL_REMOVE       20315
#define IDS_DISCOVERY_QUERY             20316
#define IDS_DISCOVERY_SUBMIT            20317
#define IDS_DISCOVERY_UPDATING          20318
#define IDS_DISCOVERY_WEB_SUCCESS       20319
#define IDS_ED2K_CLIENT_ACCEPTED        20320
#define IDS_ED2K_CLIENT_BAD_PACKET      20321
#define IDS_ED2K_CLIENT_CLOSED          20322
#define IDS_ED2K_CLIENT_CONNECTING      20323
#define IDS_ED2K_CLIENT_CONNECT_TIMEOUT 20324
#define IDS_ED2K_CLIENT_DISABLED        20325
#define IDS_ED2K_CLIENT_DROPPED         20326
#define IDS_ED2K_CLIENT_HANDSHAKE_FAIL  20327
#define IDS_ED2K_CLIENT_HANDSHAKE_TIMEOUT 20328
#define IDS_ED2K_CLIENT_SENT_HASHSET    20329
#define IDS_ED2K_CLIENT_WRONG_GUID      20330
#define IDS_ED2K_EPI_ALREADY            20331
#define IDS_ED2K_EPI_CANT_OPEN_PART     20332
#define IDS_ED2K_EPI_COPY_FINISHED      20333
#define IDS_ED2K_EPI_COPY_START         20334
#define IDS_ED2K_EPI_DISK_SPACE         20335
#define IDS_ED2K_EPI_FILE_CREATED       20336
#define IDS_ED2K_EPI_FILE_FAILED        20337
#define IDS_ED2K_EPI_FILE_OLD           20338
#define IDS_ED2K_EPI_FILE_START         20339
#define IDS_ED2K_EPI_FINISHED           20340
#define IDS_ED2K_EPI_FOLDER             20341
#define IDS_ED2K_EPI_START              20342
#define IDS_ED2K_EPI_DETECTED           20344
#define IDS_ED2K_SERVER_CONNECTED       20345
#define IDS_ED2K_SERVER_CONNECTING      20346
#define IDS_ED2K_SERVER_IDCHANGE        20347
#define IDS_ED2K_SERVER_IDENT           20348
#define IDS_ED2K_SERVER_MESSAGE         20349
#define IDS_ED2K_SERVER_ONLINE          20350
#define IDS_ED2K_SERVER_REFUSED         20351
#define IDS_ED2K_SERVER_REJECTED        20352
#define IDS_FILE_PROPERTIES             20354
#define IDS_FILTER_DELETE_CONFIRM       20355
#define IDS_FILTER_REPLACE              20356
#define IDS_FILTER_NO_NAME              20358
#define IDS_GRAPH_CONNECTION_ERRORS     20360
#define IDS_GRAPH_DOWNLOADS_BANDWIDTH   20361
#define IDS_GRAPH_DOWNLOADS_FILES       20362
#define IDS_GRAPH_DOWNLOADS_TRANSFERS   20363
#define IDS_GRAPH_GNUTELLA_BANDWIDTH_IN 20364
#define IDS_GRAPH_GNUTELLA_BANDWIDTH_OUT 20365
#define IDS_GRAPH_GNUTELLA_CONNECTIONS  20366
#define IDS_GRAPH_GNUTELLA_CONNECTIONS_ALL 20367
#define IDS_GRAPH_GNUTELLA_DROPPED      20368
#define IDS_GRAPH_GNUTELLA_LOST         20369
#define IDS_GRAPH_GNUTELLA_PACKETS_IN   20370
#define IDS_GRAPH_GNUTELLA_PACKETS_OUT  20371
#define IDS_GRAPH_GNUTELLA_PINGS        20372
#define IDS_GRAPH_GNUTELLA_PONGS        20373
#define IDS_GRAPH_GNUTELLA_QUERIES      20374
#define IDS_GRAPH_GNUTELLA_QUERIES_PROCESSED 20375
#define IDS_GRAPH_GNUTELLA_ROUTED       20376
#define IDS_GRAPH_TOTAL_BANDWIDTH_IN    20377
#define IDS_GRAPH_TOTAL_BANDWIDTH_OUT   20378
#define IDS_GRAPH_TOTAL_BANDWIDTH_TCP_IN 20379
#define IDS_GRAPH_TOTAL_BANDWIDTH_TCP_OUT 20380
#define IDS_GRAPH_TOTAL_BANDWIDTH_UDP_IN 20381
#define IDS_GRAPH_TOTAL_BANDWIDTH_UDP_OUT 20382
#define IDS_GRAPH_UPLOADS_BANDWIDTH     20383
#define IDS_GRAPH_UPLOADS_TRANSFERS     20384
#define IDS_HANDSHAKE_BACK2LEAF         20385
#define IDS_HANDSHAKE_BOOTSTRAP         20386
#define IDS_HANDSHAKE_CANTBEPEER        20387
#define IDS_HANDSHAKE_FAIL              20388
#define IDS_HANDSHAKE_GOTLEAF           20389
#define IDS_HANDSHAKE_GOTPEER           20390
#define IDS_HANDSHAKE_IAMLEAF           20391
#define IDS_HANDSHAKE_NEEDAPEER         20392
#define IDS_HANDSHAKE_NOTG2             20393
#define IDS_HANDSHAKE_NOULTRAPEER       20394
#define IDS_HANDSHAKE_ONLINE            20395
#define IDS_HANDSHAKE_ONLINE_G2         20396
#define IDS_HANDSHAKE_REJECTED          20397
#define IDS_HANDSHAKE_SURPLUS           20398
#define IDS_HANDSHAKE_TIMEOUT           20399
#define IDS_HASH_MESSAGE                20400
#define IDS_INFO_REMEMBER               20401
#define IDS_IRC_ADDCHANNEL              20402
#define IDS_IRC_CHANLIST                20403
#define IDS_IRC_HEADERINPUT             20404
#define IDS_IRC_HEADERSUBTITLE          20405
#define IDS_IRC_HEADERTITLE             20406
#define IDS_IRC_REMOVECHANNEL           20407
#define IDS_IRC_USERLIST                20408
#define IDS_LIBHEAD_HOME                20410
#define IDS_LIBHEAD_EXPLORE_FOLDER      20411
#define IDS_LIBHEAD_EXPLORE_MANY        20412
#define IDS_LIBPANEL_MULTIPLE_FILES     20413
#define IDS_LIBPANEL_MULTIPLE_FOLDERS   20414
#define IDS_LIBPANEL_NO_SELECTION       20415
#define IDS_LIBPANEL_RATE_FILE          20416
#define IDS_LIBPANEL_RECENT_ADDITIONS   20417
#define IDS_LIBRARY_ALBUM_ALBUM         20418
#define IDS_LIBRARY_ALBUM_ARTIST        20419
#define IDS_LIBRARY_ALBUM_BITRATE       20420
#define IDS_LIBRARY_ALBUM_LENGTH        20421
#define IDS_LIBRARY_ALBUM_RATING        20422
#define IDS_LIBRARY_ALBUM_TITLE         20423
#define IDS_LIBRARY_ALBUM_TRACK         20424
#define IDS_LIBRARY_COLLECTION_CANT_INSTALL 20425
#define IDS_LIBRARY_COLLECTION_DOWNLOAD_ALL 20426
#define IDS_LIBRARY_COLLECTION_INSTALLED 20427
#define IDS_LIBRARY_COLLECTION_INVALID  20428
#define IDS_LIBRARY_COLLECTION_LOCKDOWN 20429
#define IDS_LIBRARY_CONFIRM_EXECUTE     20430
#define IDS_LIBRARY_DELETE_FOLDER       20432
#define IDS_LIBRARY_DELETE_FAIL         20433
#define IDS_LIBRARY_DOWNLOADS_ADD       20434
#define IDS_LIBRARY_DOWNLOADS_SHARE     20435
#define IDS_LIBRARY_ADD_FOLDER          20436
#define IDS_LIBRARY_GHOST_FILE          20437
#define IDS_LIBRARY_METADATA_EDIT       20438
#define IDS_LIBRARY_METADATA_MANY       20439
#define IDS_LIBRARY_MOVE_FAIL           20440
#define IDS_LIBRARY_RENAME_FAIL         20441
#define IDS_LIBRARY_TARGET_EXISTS       20442
#define IDS_LIBRARY_TYPE_FILTER_ALL     20443
#define IDS_LIBRARY_URI_COPY            20444
#define IDS_LIBRARY_URI_EXPORT          20445
#define IDS_LIBRARY_VERIFY_FAIL         20446
#define IDS_LIBRARY_VERIFY_FIX          20447
#define IDS_LIBRARY_SHARED              20448
#define IDS_LIBRARY_UNSHARED            20449
#define IDS_LIBRARY_SUBFOLDER_IN_LIBRARY 20450
#define IDS_MEDIA_EMPTY                 20451
#define IDS_MEDIA_FILTER                20452
#define IDS_MEDIA_LOAD_FAIL             20453
#define IDS_MEDIA_LOAD_FAIL_HELP        20454
#define IDS_MEDIA_PARTIAL_RENDER        20455
#define IDS_MEDIA_PLAYLIST              20456
#define IDS_MEDIA_PLUGIN_CREATE         20457
#define IDS_MEDIA_PLAYER                20458
#define IDS_MEDIA_TIMESPLIT             20459
#define IDS_MEDIA_TITLE                 20460
#define IDS_MEDIAVIS_NOVIS              20462
#define IDS_MONITOR_ACTION_CANCEL       20470
#define IDS_MONITOR_ACTION_OPEN         20471
#define IDS_MONITOR_COMPLETED_WORD      20472
#define IDS_MONITOR_ESTIMATED_TIME      20473
#define IDS_MONITOR_NUMBER_REVIEWS      20474
#define IDS_MONITOR_NUMBER_SOURCES      20475
#define IDS_MONITOR_NO_SOURCES          20476
#define IDS_MONITOR_TIME_DH             20477
#define IDS_MONITOR_TIME_HM             20478
#define IDS_MONITOR_TIME_MS             20479
#define IDS_MONITOR_TIME_S              20480
#define IDS_MONITOR_TOTAL_SPEED         20481
#define IDS_MONITOR_VOLUME_DOWNLOADED   20482
#define IDS_MONITOR_VOLUME_UPLOADED     20483
#define IDS_MONITORBAR_LIMIT_IN         20484
#define IDS_MONITORBAR_LIMIT_OUT        20485
#define IDS_MULTIPLE                    20490
#define IDS_MULTIPLE_VALUES             20491
#define IDS_PROFILE_NO_LOCATION         20494
#define IDS_PROFILE_NO_NICK             20495
#define IDS_PROFILE_NO_VITALS           20496
#define IDS_NEW_FOLDER                  20499
#define IDS_NEIGHBOURS_CONNECT          20500
#define IDS_NEIGHBOURS_NOT_CONNECTED    20501
#define IDS_NEIGHBOUR_CLOSING           20502
#define IDS_NEIGHBOUR_COMPRESSION       20503
#define IDS_NEIGHBOUR_COMPRESSION_DF    20504
#define IDS_NEIGHBOUR_COMPRESSION_NONE  20505
#define IDS_NEIGHBOUR_CONNECTING        20506
#define IDS_NEIGHBOUR_CURRENT           20507
#define IDS_NEIGHBOUR_DCHUB             20509
#define IDS_NEIGHBOUR_ED2K_HIGH         20510
#define IDS_NEIGHBOUR_ED2K_HIGHID       20511
#define IDS_NEIGHBOUR_ED2K_LOW          20512
#define IDS_NEIGHBOUR_ED2K_LOWID        20513
#define IDS_NEIGHBOUR_ED2K_SERVER       20514
#define IDS_NEIGHBOUR_G1LEAF            20515
#define IDS_NEIGHBOUR_G1PEER            20516
#define IDS_NEIGHBOUR_G1PP              20517
#define IDS_NEIGHBOUR_G1LU              20518
#define IDS_NEIGHBOUR_G1UL              20519
#define IDS_NEIGHBOUR_G1ULTRA           20520
#define IDS_NEIGHBOUR_G2HUB             20521
#define IDS_NEIGHBOUR_G2LEAF            20522
#define IDS_NEIGHBOUR_G2PEER            20524
#define IDS_NEIGHBOUR_G2LH              20525
#define IDS_NEIGHBOUR_G2HH              20526
#define IDS_NEIGHBOUR_G2HL              20527
#define IDS_NEIGHBOUR_HANDSHAKE         20530
#define IDS_NEIGHBOUR_HANDSHAKING       20531
#define IDS_NEIGHBOUR_INBOUND           20532
#define IDS_NEIGHBOUR_OUTBOUND          20533
#define IDS_NEIGHBOUR_TOTAL             20534
#define IDS_NEIGHBOUR_RATIO             20535
#define IDS_NEIGHBOUR_REJECTED          20536
#define IDS_NEIGHBOUR_UNKNOWN           20538
#define IDS_NETWORK_CONNECT             20540
#define IDS_NETWORK_CONNECTING          20541
#define IDS_NETWORK_CONNECTED           20542
#define IDS_NETWORK_DISCONNECT          20543
#define IDS_NETWORK_DISCONNECTING       20544
#define IDS_NETWORK_DISCONNECTED        20545
#define IDS_NETWORK_DISCONNECT_CONFIRM  20546
#define IDS_NETWORK_DISABLE_G2          20547
#define IDS_NETWORK_CANT_LISTEN         20548
#define IDS_NETWORK_CANT_OUTGOING       20549
#define IDS_NETWORK_BANDWIDTH_LOW       20550
#define IDS_NETWORK_FIREWALLED          20551
#define IDS_NETWORK_FORCE_HUB           20552
#define IDS_NETWORK_LISTENING_TCP       20553
#define IDS_NETWORK_LISTENING_UDP       20554
#define IDS_NETWORK_OUTGOING            20555
#define IDS_NETWORK_RESOLVE_FAIL        20556
#define IDS_NETWORK_RESOLVING           20557
#define IDS_NETWORK_SEARCH_SENT         20558
#define IDS_SECURITY_BANNED_USERAGENT   20559
#define IDS_SECURITY_BLOCKED            20560
#define IDS_SECURITY_OUTGOING           20561
#define IDS_SECURITY_ADDED              20562
#define IDS_SECURITY_EXISTS             20563
#define IDS_NETWORK_STARTUP             20564
#define IDS_NETWORK_UNLIMIT             20565
#define IDS_NETWORK_UPNP_FAILED         20566
#define IDS_NETWORK_ALWAYS              20568
#define IDS_PROTOCOL_BAD_HIT            20570
#define IDS_PROTOCOL_BAD_QUERY          20571
#define IDS_PROTOCOL_HIGH_TTL           20572
#define IDS_PROTOCOL_GGEP_REQUIRED      20574
#define IDS_PROTOCOL_QRP_FAILED         20575
#define IDS_PROTOCOL_QRP_SENT           20576
#define IDS_PROTOCOL_QRP_UNEXPECTED     20577
#define IDS_PROTOCOL_QRP_UPDATED        20578
#define IDS_PROTOCOL_LEAF_FORWARD       20580
#define IDS_PROTOCOL_SIZE_PACKET        20582
#define IDS_PROTOCOL_TOO_LARGE          20584
#define IDS_PROTOCOL_EXCEEDS_LIMIT      20585
#define IDS_PROTOCOL_UNKNOWN            20586
#define IDS_PROTOCOL_ZERO_PONG          20587
#define IDS_PROTOCOL_ZERO_PUSH          20588
#define IDS_SECURITY_DEFAULT            20589
#define IDS_SECURITY_ACCEPT             20590
#define IDS_SECURITY_DENY               20591
#define IDS_SECURITY_ANY                20592
#define IDS_SECURITY_ALL                20593
#define IDS_SECURITY_HASH               20594
#define IDS_SECURITY_LIST               20595
#define IDS_SECURITY_NOEXPIRE           20596
#define IDS_SECURITY_SESSION            20597
#define IDS_SECURITY_REMOVE_CONFIRM     20598
#define IDS_SECURITY_TIP_NETMASK        20599
#define IDS_SCHEDULER_BANDWIDTH_FULL    20600
#define IDS_SCHEDULER_BANDWIDTH_LIMITED 20601
#define IDS_SCHEDULER_BANDWIDTH_STOP    20602
#define IDS_SCHEDULER_SYSTEM_EXIT       20603
#define IDS_SCHEDULER_SYSTEM_SHUTDOWN   20604
#define IDS_SCHEDULER_SYSTEM_DIALUP_OFF 20605
#define IDS_SCHEDULER_SYSTEM_NOTICE     20606
#define IDS_SCHEDULER_REMINDER_NOTICE   20607
#define IDS_SCHEDULER_REMOVEALL_CONFIRM 20608
#define IDS_SCHEDULER_TIME_PASSED       20609
#define IDS_SCHEDULER_SELECTADAY        20610
#define IDS_SCHEDULER_SELECTTASK        20611
#define IDS_SCHEDULER_TASK_WAITING      20614
#define IDS_SCHEDULER_TASK_DONETODAY    20615
#define IDS_SCHEDULER_TASK_DONE         20616
#define IDS_SCHEDULER_TASK_NONE         20618
#define IDS_SEARCH_ACTIVE               20620
#define IDS_SEARCH_AGAIN                20621
#define IDS_SEARCH_ALL_NETWORKS         20622
#define IDS_SEARCH_CLEAR_PREVIOUS       20623
#define IDS_SEARCH_DETAILS_EMPTY        20624
#define IDS_SEARCH_DETAILS_WRITES       20625
#define IDS_SEARCH_DETAILS_RATES        20626
#define IDS_SEARCH_DETAILS_PREVIEW      20627
#define IDS_SEARCH_DETAILS_PREVIEWING   20628
#define IDS_SEARCH_DETAILS_PREVIEW_FAILED 20629
#define IDS_SEARCH_DETAILS_REVIEWS_MANY 20630
#define IDS_SEARCH_DETAILS_REVIEWS_ONE  20631
#define IDS_SEARCH_DETAILS_SOURCES_MANY 20632
#define IDS_SEARCH_DETAILS_SOURCES_ONE  20633
#define IDS_SEARCH_EMPTY                20634
#define IDS_SEARCH_FILTERED             20635
#define IDS_SEARCH_NONE                 20636
#define IDS_SEARCH_NO_METADATA          20637
#define IDS_SEARCH_NO_SCHEMA            20638
#define IDS_SEARCH_PAD_CLEAR_HISTORY    20640
#define IDS_SEARCH_PAD_HEADER           20641
#define IDS_SEARCH_PAD_TYPE             20642
#define IDS_SEARCH_PAD_WORDS            20643
#define IDS_SEARCH_PANEL_ADVANCED       20644
#define IDS_SEARCH_PANEL_AFT            20645
#define IDS_SEARCH_PANEL_CLEAR          20646
#define IDS_SEARCH_PANEL_FILTERED       20647
#define IDS_SEARCH_PANEL_HIDE           20648
#define IDS_SEARCH_PANEL_INPUT_CAPTION  20650
#define IDS_SEARCH_PANEL_INPUT_1        20651
#define IDS_SEARCH_PANEL_INPUT_2        20652
#define IDS_SEARCH_PANEL_INPUT_3        20653
#define IDS_SEARCH_PANEL_INPUT_4        20654
#define IDS_SEARCH_PANEL_INPUT_5        20655
#define IDS_SEARCH_PANEL_MORE           20656
#define IDS_SEARCH_PANEL_SHOW           20657
#define IDS_SEARCH_PANEL_START          20658
#define IDS_SEARCH_PANEL_STOP           20659
#define IDS_SEARCH_PANEL_RESULTS_NONE   20660
#define IDS_SEARCH_PANEL_RESULTS_ACTIVE 20661
#define IDS_SEARCH_PANEL_RESULTS_INACTIVE 20662
#define IDS_SEARCH_PANEL_RESULTS_CAPTION 20663
#define IDS_SEARCH_PANEL_RESULTS_FORMAT 20664
#define IDS_SEARCH_PANEL_RESULTS_FOUND  20665
#define IDS_SEARCH_PANEL_RESULTS_STATUS 20666
#define IDS_SEARCH_PANEL_SEARCHING      20668
#define IDS_SEARCH_PLAIN_TEXT           20669
#define IDS_SEARCH_WORKING              20670
#define IDS_SELECT_ED2K_TEMP_FOLDER     20672
#define IDS_SETTINGS_AUTOMATIC_IP       20673
#define IDS_SETTINGS_FILEPATH_NOT_SAME  20674
#define IDS_SETTINGS_FILEPATH_TOO_LONG  20675
#define IDS_SETTINGS_INCOMPLETE_LIBRARY 20676
#define IDS_SETTINGS_NEED_BANDWIDTH     20677
#define IDS_SETTINGS_WARN_QUEUELIMIT    20678
#define IDS_SETTINGS                    20680
#define IDS_REMOTE_DISABLED             20682
#define IDS_REMOTE_ENABLED              20684
#define IDS_REMOTE_UNAVAILABLE          20685
#define IDS_SKIN_LOAD                   20690
#define IDS_SKIN_ERROR                  20691
#define IDS_SKIN_DELETE                 20692
#define IDS_SCHEMA_LOAD_ERROR           20698
#define IDS_SCHEMAS                     20699
#define IDS_STATUS_BAR_BANDWIDTH        20700
#define IDS_STATUS_BAR_CONNECTED        20701
#define IDS_STATUS_BAR_CONNECTED_HUB    20702
#define IDS_STATUS_BAR_CONNECTED_HUB_UP 20703
#define IDS_STATUS_BAR_CONNECTED_UP     20704
#define IDS_STATUS_BAR_CONNECTED_SIMPLE 20705
#define IDS_STATUS_BAR_CONNECTING       20706
#define IDS_STATUS_BAR_DISCONNECTED     20707
#define IDS_STATUS_ACTIVE               20708
#define IDS_STATUS_INACTIVE             20709
#define IDS_STATUS_CLEARING             20710
#define IDS_STATUS_CANTMOVE             20711
#define IDS_STATUS_CHOKED               20712
#define IDS_STATUS_ENQUEUE              20713
#define IDS_STATUS_FILEERROR            20714
#define IDS_STATUS_HASHSET              20715
#define IDS_STATUS_METADATA             20716
#define IDS_STATUS_RESPONSE             20717
#define IDS_STATUS_MOVING               20718
#define IDS_STATUS_CREATING             20719
#define IDS_STATUS_COMPLETED            20720
#define IDS_STATUS_CONNECTING           20721
#define IDS_STATUS_DOWNLOADING          20722
#define IDS_STATUS_BUSY                 20723
#define IDS_STATUS_NEXT                 20724
#define IDS_STATUS_Q                    20725
#define IDS_STATUS_QUEUED               20726
#define IDS_STATUS_PAUSED               20727
#define IDS_STATUS_PENDING              20728
#define IDS_STATUS_REQUESTING           20729
#define IDS_STATUS_SEARCHING            20730
#define IDS_STATUS_SEEDING              20731
#define IDS_STATUS_SOURCE               20732
#define IDS_STATUS_SOURCES              20733
#define IDS_STATUS_SOURCES_FEW          20734
#define IDS_STATUS_SOURCES_ONES         20735
#define IDS_STATUS_NOSOURCES            20736
#define IDS_STATUS_TIGERTREE            20740
#define IDS_STATUS_TORRENT              20741
#define IDS_STATUS_TRACKERDOWN          20742
#define IDS_STATUS_UNINTERESTED         20743
#define IDS_STATUS_UNKNOWN              20744
#define IDS_STATUS_UNSUPPORTED          20745
#define IDS_STATUS_UNVERIFIED           20746
#define IDS_STATUS_VERIFIED             20747
#define IDS_STATUS_VERIFYING            20748
#define IDS_SYSTEM_MESSAGE              20750
#define IDS_TABBAR_CONNECTED            20751
#define IDS_TABBAR_NOT_CONNECTED        20752
#define IDS_TEMPLATE_DELETE             20755
#define IDS_TIP_PRIORITY                20760
#define IDS_TIP_BOGUS                   20762
#define IDS_TIP_EXISTS_BLACKLISTED      20763
#define IDS_TIP_EXISTS_DELETED          20764
#define IDS_TIP_EXISTS_DOWNLOAD         20765
#define IDS_TIP_EXISTS_LIBRARY          20766
#define IDS_TIP_FILE_BUSY               20767
#define IDS_TIP_FILE_FIREWALLED         20768
#define IDS_TIP_FILE_UNSTABLE           20769
#define IDS_TIP_FOLDER                  20770
#define IDS_TIP_HITS                    20771
#define IDS_TIP_LOCATION                20772
#define IDS_TIP_LIBRARY_PERCENT         20773
#define IDS_TIP_NA                      20774
#define IDS_TIP_NEXT                    20775
#define IDS_TIP_NOHASHSET               20776
#define IDS_TIP_PARTIAL                 20777
#define IDS_TIP_QUEUE                   20778
#define IDS_TIP_SIZE                    20780
#define IDS_TIP_SOURCE_BUSY             20781
#define IDS_TIP_SOURCE_FIREWALLED       20782
#define IDS_TIP_SOURCE_UNSTABLE         20783
#define IDS_TIP_SPEED                   20784
#define IDS_TIP_STATUS                  20785
#define IDS_TIP_TODAYTOTAL              20786
#define IDS_TIP_TOTAL_FILES             20787
#define IDS_TIP_TOTAL_VOLUME            20788
#define IDS_TIP_TRANSFER                20789
#define IDS_TIP_TYPE                    20790
#define IDS_TIP_UNTRUSTED               20791
#define IDS_TIP_UPLOADS                 20792
#define IDS_TIP_URL                     20793
#define IDS_TIP_USERAGENT               20794
#define IDS_TRAY_TIP                    20795
#define IDS_FOLDER_TIP                  20796
#define IDS_UPGRADE_LAUNCH              20798
#define IDS_UPGRADE_NO_NEW              20799
#define IDS_UPLOAD_ABOUT                20800
#define IDS_UPLOAD_ACCEPTED             20801
#define IDS_UPLOAD_BROWSE               20802
#define IDS_UPLOAD_BROWSER              20803
#define IDS_UPLOAD_BROWSE_BUSY          20804
#define IDS_UPLOAD_BROWSE_DENIED        20805
#define IDS_UPLOAD_BUSY_FAST            20806
#define IDS_UPLOAD_BUSY_HOST            20807
#define IDS_UPLOAD_BUSY_OLD             20808
#define IDS_UPLOAD_BUSY_QUEUE           20809
#define IDS_UPLOAD_BUSY_LIBRARY         20810
#define IDS_UPLOAD_BAD_RANGE            20811
#define IDS_UPLOAD_CANTOPEN             20812
#define IDS_UPLOAD_CONNECT              20813
#define IDS_UPLOAD_CONNECT_ERROR        20814
#define IDS_UPLOAD_CONTENT              20815
#define IDS_UPLOAD_DROPPED              20816
#define IDS_UPLOAD_DROPPED_NEWER        20817
#define IDS_UPLOAD_DROPPED_OLDER        20818
#define IDS_UPLOAD_DISABLED             20819
#define IDS_UPLOAD_DELETED              20820
#define IDS_UPLOAD_FILE                 20821
#define IDS_UPLOAD_FILENOTFOUND         20822
#define IDS_UPLOAD_FINISHED             20823
#define IDS_UPLOAD_GIV                  20824
#define IDS_UPLOAD_HASH_MISMATCH        20825
#define IDS_UPLOAD_HEADERS              20826
#define IDS_UPLOAD_METADATA_SEND        20827
#define IDS_UPLOAD_NOHTTP               20828
#define IDS_UPLOAD_PARTIAL_CONTENT      20830
#define IDS_UPLOAD_PREVIEW_BUSY         20832
#define IDS_UPLOAD_PREVIEW_DYNAMIC      20833
#define IDS_UPLOAD_PREVIEW_EMPTY        20834
#define IDS_UPLOAD_PREVIEW_SEND         20835
#define IDS_UPLOAD_PUSH_BUSY            20836
#define IDS_UPLOAD_QUEUED               20838
#define IDS_UPLOAD_QUEUE_DROP           20840
#define IDS_UPLOAD_QUEUE_NEW            20841
#define IDS_UPLOAD_QUEUE_COMPLETE       20842
#define IDS_UPLOAD_QUEUE_DC_GUARD       20843
#define IDS_UPLOAD_QUEUE_ED2K_CORE      20844
#define IDS_UPLOAD_QUEUE_ED2K_GUARD     20845
#define IDS_UPLOAD_QUEUE_ED2K_PARTIALS  20846
#define IDS_UPLOAD_QUEUE_HISTORY        20847
#define IDS_UPLOAD_QUEUE_HTTP_GUARD     20848
#define IDS_UPLOAD_QUEUE_LIBRARY        20849
#define IDS_UPLOAD_QUEUE_LARGE_FILES    20850
#define IDS_UPLOAD_QUEUE_MEDIUM_FILES   20851
#define IDS_UPLOAD_QUEUE_SMALL_FILES    20852
#define IDS_UPLOAD_QUEUE_PARTIAL_FILES  20853
#define IDS_UPLOAD_QUEUE_PARTIAL        20854
#define IDS_UPLOAD_QUEUE_QUEUE          20855
#define IDS_UPLOAD_QUEUE_TORRENT        20856
#define IDS_UPLOAD_QUEUE_TIMEOUT        20857
#define IDS_UPLOAD_REQUEST_TIMEOUT      20858
#define IDS_UPLOAD_TRAFFIC_TIMEOUT      20859
#define IDS_UPLOAD_TIGER_SEND           20860
#define IDS_UPLOAD_CANCEL_ED2K          20861
#define IDS_UPLOAD_REMOVE               20862
#define IDS_URL_ADD                     20864
#define IDS_URL_BROWSE                  20865
#define IDS_URL_CONNECT                 20866
#define IDS_URL_FILENAME                20867
#define IDS_URL_HOST                    20868
#define IDS_URL_PORT                    20869
#define IDS_URL_PARSE_ERROR             20870
#define IDS_URL_RECEIVED                20871
#define IDS_URL_TYPE                    20872
#define IDS_URL_URL                     20874
#define IDS_URL_UNSPECIFIED             20875
#define IDS_USER_PROFILE                20880
#define IDS_LOCK_TIMEOUT                20881
#define IDS_TOO_MANY_FILES              20882
#define IDS_NO_URN_AVAILABLE            20883
#define IDS_UPNP_SERVICES_ERROR         20884
#define IDS_VIEW_MODE_CONFIRM           20885
#define IDS_WARNING_RTL                 20886
#define IDS_WIZARD                      20890
#define IDS_WIZARD_EXIT                 20891
#define IDS_WIZARD_ED2K                 20892
#define IDS_WIZARD_DISCOVERY            20893
#define IDS_WIZARD_TIP_PORT             20895
#define IDS_WIZARD_NEED_SPEED           20896
#define IDS_WIZARD_SHARE_ALREADY        20897
#define IDS_WIZARD_SHARE_CONFIRM        20898
#define IDS_WIZARD_YEARS_OLD            20899
#define ID_TAB_HOME                     40001
#define ID_TAB_CONNECT                  40002
#define ID_TAB_TRANSFERS                40003
#define ID_TAB_SEARCH                   40004
#define ID_TAB_NETWORK                  40005
#define ID_TAB_LIBRARY                  40006
#define ID_TAB_MEDIA                    40007
#define ID_TAB_IRC                      40008
#define ID_TAB_MENU                     40009
#define ID_BROWSE_FILES                 40010
#define ID_BROWSE_LAUNCH                40011
#define ID_BROWSE_PROFILE               40012
#define ID_BROWSE_REFRESH               40013
#define ID_BROWSE_STOP                  40014
#define ID_CHAT_BOLD                    40015
#define ID_CHAT_ITALIC                  40016
#define ID_CHAT_UNDERLINE               40017
#define ID_CHAT_COLOR                   40018
#define ID_CHAT_EMOTICONS               40019
#define ID_CHAT_BROWSE                  40020
#define ID_CHAT_CLEAR                   40021
#define ID_CHAT_CONNECT                 40022
#define ID_CHAT_DISCONNECT              40023
#define ID_CHAT_PRIORITY                40024
#define ID_CHAT_SEND_FILE               40025
#define ID_CHAT_TIMESTAMP               40026
#define ID_CHILD_CLOSE                  40030
#define ID_CHILD_CLOSE_HOVER            40031
#define ID_CHILD_MINIMISE               40032
#define ID_CHILD_MAXIMISE               40033
#define ID_CHILD_RESTORE                40034
#define ID_CHECKMARK                    40035
#define ID_DISCOVERY_ADD                40040
#define ID_DISCOVERY_EDIT               40041
#define ID_DISCOVERY_REMOVE             40042
#define ID_DISCOVERY_QUERY              40043
#define ID_DISCOVERY_ADVERTISE          40044
#define ID_DISCOVERY_BROWSE             40045
#define ID_DISCOVERY_BLOCKED            40046
#define ID_DISCOVERY_GNUTELLA           40047
#define ID_DISCOVERY_WEBCACHE           40048
#define ID_DISCOVERY_SERVERLIST         40049
#define ID_DOWNLOADS_ADD_SOURCE         40050
#define ID_DOWNLOADS_AUTO_CLEAR         40051
#define ID_DOWNLOADS_BOOST              40052
#define ID_DOWNLOADS_CLEAR              40053
#define ID_DOWNLOADS_CLEAR_COMPLETE     40054
#define ID_DOWNLOADS_CLEAR_COMPLETED    40055
#define ID_DOWNLOADS_CLEAR_INCOMPLETE   40056
#define ID_DOWNLOADS_CLEAR_PAUSED       40057
#define ID_DOWNLOADS_EDIT               40058
#define ID_DOWNLOADS_ENQUEUE            40059
#define ID_DOWNLOADS_FILE_DELETE        40060
#define ID_DOWNLOADS_FILTER_ACTIVE      40061
#define ID_DOWNLOADS_FILTER_ALL         40062
#define ID_DOWNLOADS_FILTER_MENU        40063
#define ID_DOWNLOADS_FILTER_PAUSED      40064
#define ID_DOWNLOADS_FILTER_QUEUED      40065
#define ID_DOWNLOADS_FILTER_SEEDS       40066
#define ID_DOWNLOADS_FILTER_SOURCES     40067
#define ID_DOWNLOADS_FOLDER             40068
#define ID_DOWNLOADS_HELP               40069
#define ID_DOWNLOADS_LAUNCH             40070
#define ID_DOWNLOADS_LAUNCH_COMPLETE    40071
#define ID_DOWNLOADS_LAUNCH_COPY        40072
#define ID_DOWNLOADS_MERGE              40073
#define ID_DOWNLOADS_MONITOR            40074
#define ID_DOWNLOADS_MOVE_UP            40075
#define ID_DOWNLOADS_MOVE_DOWN          40076
#define ID_DOWNLOADS_MOVE_TOP           40077
#define ID_DOWNLOADS_MOVE_BOTTOM        40078
#define ID_DOWNLOADS_RATE               40079
#define ID_DOWNLOADS_PAUSE              40080
#define ID_DOWNLOADS_RESUME             40081
#define ID_DOWNLOADS_REMOTE_PREVIEW     40082
#define ID_DOWNLOADS_SHARE              40083
#define ID_DOWNLOADS_SOURCES            40084
#define ID_DOWNLOADS_SHOW_SOURCES       40085
#define ID_DOWNLOADS_VIEW_REVIEWS       40086
#define ID_DOWNLOADS_SETTINGS           40088
#define ID_DOWNLOADS_URI                40089
#define ID_DOWNLOAD_GROUP_CLEAR         40090
#define ID_DOWNLOAD_GROUP_MOVELEFT      40091
#define ID_DOWNLOAD_GROUP_MOVERIGHT     40092
#define ID_DOWNLOAD_GROUP_NEW           40093
#define ID_DOWNLOAD_GROUP_OPEN          40094
#define ID_DOWNLOAD_GROUP_PAUSE         40095
#define ID_DOWNLOAD_GROUP_PROPERTIES    40096
#define ID_DOWNLOAD_GROUP_REMOVE        40097
#define ID_DOWNLOAD_GROUP_RESUME        40098
#define ID_DOWNLOAD_GROUP_SHOW          40099
#define ID_OPEN_DOWNLOADS_FOLDER        40100
#define ID_HELP_ABOUT                   40101
#define ID_HELP_CODEC                   40102
#define ID_HELP_CONNECTIONFAIL          40103
#define ID_HELP_DISKWRITEFAIL           40104
#define ID_HELP_DISKSPACE               40105
#define ID_HELP_DONATE                  40106
#define ID_HELP_DONKEYSERVERS           40107
#define ID_HELP_FAQ                     40109
#define ID_HELP_FORUMS                  40110
#define ID_HELP_FORUMS_LOCAL            40111
#define ID_HELP_GUIDE                   40112
#define ID_HELP_HOMEPAGE                40113
#define ID_HELP_PROMOTE                 40114
#define ID_HELP_ROUTER                  40115
#define ID_HELP_SCHEDULER               40116
#define ID_HELP_SECURITY                40117
#define ID_HELP_TEST                    40118
#define ID_HELP_UPDATE                  40119
#define ID_HELP_VERSION_CHECK           40120
#define ID_HELP_WEB_1                   40121
#define ID_HELP_WEB_2                   40122
#define ID_HELP_WEB_3                   40123
#define ID_HELP_WEB_4                   40124
#define ID_HELP_WEB_SKINS               40125
#define ID_HELP_WEB_BITPRINTS           40126
#define ID_HELP_WEB_LOVE                40127
#define ID_HELP_WARNINGS                40128
#define ID_HELP_STARTPAGE               40129
#define ID_HOSTCACHE_CONNECT            40130
#define ID_HOSTCACHE_DISCONNECT         40131
#define ID_HOSTCACHE_G2_HORIZON         40132
#define ID_HOSTCACHE_G2_CACHE           40133
#define ID_HOSTCACHE_G1_CACHE           40134
#define ID_HOSTCACHE_DC_CACHE           40135
#define ID_HOSTCACHE_BT_CACHE           40136
#define ID_HOSTCACHE_KAD_CACHE          40137
#define ID_HOSTCACHE_ED2K_CACHE         40138
#define ID_HOSTCACHE_FILE_DOWNLOAD      40139
#define ID_HOSTCACHE_IMPORT             40140
#define ID_HOSTCACHE_REMOVE             40141
#define ID_HOSTCACHE_PRIORITY           40142
#define ID_HITMONITOR_CLEAR             40144
#define ID_HITMONITOR_PAUSE             40145
#define ID_HITMONITOR_SEARCH            40146
#define ID_IMPORT_DOWNLOADS             40148
#define ID_IRC_CONNECT                  40150
#define ID_IRC_DISCONNECT               40151
#define ID_IRC_CLOSETAB                 40152
#define ID_IRC_SETTINGS                 40153
#define ID_IRC_SENDTEXT                 40154
#define ID_IRC_EDITBOX                  40155
#define ID_IRC_ADD                      40156
#define ID_IRC_REMOVE                   40158
#define ID_IRC_OP                       40160
#define ID_IRC_DEOP                     40161
#define ID_IRC_VOICE                    40162
#define ID_IRC_DEVOICE                  40163
#define ID_IRC_SLAP                     40164
#define ID_IRC_BAN                      40165
#define ID_IRC_KICK                     40166
#define ID_IRC_KICKWHY                  40167
#define ID_IRC_BANKICK                  40168
#define ID_IRC_BANKICKWHY               40169
#define ID_IRC_UNBAN                    40170
#define ID_IRC_IGNORE                   40171
#define ID_IRC_UNIGNORE                 40172
#define ID_IRC_INFO                     40173
#define ID_IRC_PING                     40174
#define ID_IRC_QUERY                    40175
#define ID_IRC_TIME                     40176
#define ID_IRC_VERSION                  40177
#define ID_IRC_WHOIS                    40178
#define ID_IRC_BROWSE                   40179
#define ID_LIBRARY_ALBUM_OPEN           40200
#define ID_LIBRARY_ALBUM_DELETE         40201
#define ID_LIBRARY_ALBUM_PROPERTIES     40202
#define ID_LIBRARY_BITPRINTS_DOWNLOAD   40203
#define ID_LIBRARY_BITPRINTS_WEB        40204
#define ID_LIBRARY_COLUMNS              40205
#define ID_LIBRARY_CREATETORRENT        40206
#define ID_LIBRARY_EXPORT_COLLECTION    40207
#define ID_LIBRARY_EXPLORE              40208
#define ID_LIBRARY_ENQUEUE              40209
#define ID_LIBRARY_LAUNCH               40210
#define ID_LIBRARY_LAUNCH_FOLDER        40211
#define ID_LIBRARY_FOLDER_NEW           40212
#define ID_LIBRARY_FOLDER_DELETE        40213
#define ID_LIBRARY_FOLDER_DOWNLOAD      40214
#define ID_LIBRARY_FOLDER_ENQUEUE       40215
#define ID_LIBRARY_FOLDER_METADATA      40216
#define ID_LIBRARY_FOLDER_FILE_PROPERTIES 40217
#define ID_LIBRARY_FOLDER_PROPERTIES    40218
#define ID_LIBRARY_FOLDERS              40220
#define ID_LIBRARY_SHOW_FILE            40221
#define ID_LIBRARY_HASH_PRIORITY        40222
#define ID_LIBRARY_PANEL                40223
#define ID_LIBRARY_PARENT               40224
#define ID_LIBRARY_PROPERTIES           40225
#define ID_LIBRARY_DELETE               40226
#define ID_LIBRARY_COPY                 40227
#define ID_LIBRARY_MOVE                 40228
#define ID_LIBRARY_ADD                  40229
#define ID_LIBRARY_REMOVE               40230
#define ID_LIBRARY_RENAME               40231
#define ID_LIBRARY_REBUILD              40232
#define ID_LIBRARY_REBUILD_ANSI         40233
#define ID_LIBRARY_REBUILD_FILE         40234
#define ID_LIBRARY_REFRESH              40235
#define ID_LIBRARY_REFRESH_METADATA     40236
#define ID_LIBRARY_SCAN                 40237
#define ID_LIBRARY_SEARCH               40238
#define ID_LIBRARY_SEARCH_QUICK         40239
#define ID_LIBRARY_SEED_TORRENT         40240
#define ID_LIBRARY_SELECT_ALL           40241
#define ID_LIBRARY_SHARED_FILE          40242
#define ID_LIBRARY_SHARED_FOLDER        40243
#define ID_LIBRARY_TREE_PHYSICAL        40244
#define ID_LIBRARY_TREE_VIRTUAL         40245
#define ID_LIBRARY_CLEAR_HISTORY        40246
#define ID_LIBRARY_CLEAR_HISTORY_ALL    40247
#define ID_LIBRARY_UNLINK               40248
#define ID_LIBRARY_URI                  40249
#define ID_LIBRARY_VIEW                 40250
#define ID_LIBRARY_VIEW_ALBUM           40251
#define ID_LIBRARY_VIEW_COLLECTION      40252
#define ID_LIBRARY_VIEW_DETAIL          40253
#define ID_LIBRARY_VIEW_HOME            40254
#define ID_LIBRARY_VIEW_ICON            40255
#define ID_LIBRARY_VIEW_LIST            40256
#define ID_LIBRARY_VIEW_THUMBNAIL       40257
#define ID_LIBRARY_VIEW_TILE            40258
#define ID_MEDIA_ADD                    40260
#define ID_MEDIA_ADD_FOLDER             40261
#define ID_MEDIA_ASPECT_4_3             40262
#define ID_MEDIA_ASPECT_16_9            40263
#define ID_MEDIA_ASPECT_DEFAULT         40264
#define ID_MEDIA_CLEAR                  40265
#define ID_MEDIA_CLOSE                  40266
#define ID_MEDIA_EXPORT_COLLECTION      40267
#define ID_MEDIA_FULLSCREEN             40268
#define ID_MEDIA_MUTE                   40270
#define ID_MEDIA_OPEN                   40271
#define ID_MEDIA_NEXT                   40272
#define ID_MEDIA_PREVIOUS               40273
#define ID_MEDIA_PAUSE                  40274
#define ID_MEDIA_PLAY                   40275
#define ID_MEDIA_PLAYLIST               40276
#define ID_MEDIA_PROPERTIES             40278
#define ID_MEDIA_RATE                   40279
#define ID_MEDIA_RANDOM                 40280
#define ID_MEDIA_REPEAT                 40281
#define ID_MEDIA_REMOVE                 40282
#define ID_MEDIA_SAVE                   40283
#define ID_MEDIA_SELECT                 40284
#define ID_MEDIA_SIZE_ONE               40285
#define ID_MEDIA_SIZE_TWO               40286
#define ID_MEDIA_SIZE_HALF              40287
#define ID_MEDIA_SIZE_FILL              40288
#define ID_MEDIA_SIZE_DISTORT           40289
#define ID_MEDIA_SETTINGS               40290
#define ID_MEDIA_STATE_PAUSE            40291
#define ID_MEDIA_STATE_PLAY             40292
#define ID_MEDIA_STATE_STOP             40293
#define ID_MEDIA_STATUS                 40294
#define ID_MEDIA_STOP                   40295
#define ID_MEDIA_VIS                    40296
#define ID_MEDIA_ZOOM                   40298
#define ID_MONITOR_CLOSE                40300
#define ID_MOVETAB_FIRST                40301
#define ID_MOVETAB_LAST                 40302
#define ID_MOVETAB_LEFT                 40303
#define ID_MOVETAB_RIGHT                40304
#define ID_NEIGHBOURS_CHAT              40310
#define ID_NEIGHBOURS_DISCONNECT        40311
#define ID_NEIGHBOURS_SETTINGS          40312
#define ID_NEIGHBOURS_VIEW_ALL          40314
#define ID_NEIGHBOURS_VIEW_INCOMING     40315
#define ID_NEIGHBOURS_VIEW_OUTGOING     40316
#define ID_NEIGHBOURS_URI               40318
#define ID_NETWORK_G2                   40320
#define ID_NETWORK_G1                   40321
#define ID_NETWORK_ED2K                 40322
#define ID_NETWORK_KAD                  40323
#define ID_NETWORK_DC                   40324
#define ID_NETWORK_BT                   40325
#define ID_NETWORK_HTTP                 40326
#define ID_NETWORK_FTP                  40327
#define ID_NETWORK_NULL                 40328
#define ID_NETWORK_CONNECT              40330
#define ID_NETWORK_CONNECT_TO           40331
#define ID_NETWORK_DISCONNECT           40332
#define ID_NETWORK_BROWSE_TO            40333
#define ID_NETWORK_CHAT_TO              40334
#define ID_NETWORK_SEARCH               40335
#define ID_NETWORK_EXIT                 40336
#define ID_NETWORK_AUTO_CLOSE           40337
#define ID_SEARCHMONITOR_CLEAR          40338
#define ID_SEARCHMONITOR_PAUSE          40339
#define ID_SEARCH_SEARCH                40340
#define ID_SEARCH_STOP                  40341
#define ID_SEARCH_CLEAR                 40342
#define ID_SEARCH_CHAT                  40343
#define ID_SEARCH_COLUMNS               40344
#define ID_SEARCH_DETAILS               40345
#define ID_SEARCH_DOWNLOAD              40346
#define ID_SEARCH_DOWNLOADNOW           40348
#define ID_SEARCH_FILTER                40350
#define ID_SEARCH_FILTER_RAW            40351
#define ID_SEARCH_FILTER_REMOVE         40352
#define ID_SEARCH_FOR_ALBUM             40353
#define ID_SEARCH_FOR_ARTIST            40354
#define ID_SEARCH_FOR_SERIES            40355
#define ID_SEARCH_FOR_SIMILAR           40356
#define ID_SEARCH_FOR_THIS              40357
#define ID_SEARCH_PANEL                 40358
#define ID_SEARCH_URI                   40359
#define ID_SECURITY_BAN                 40360
#define ID_SECURITY_ADD                 40361
#define ID_SECURITY_EDIT                40362
#define ID_SECURITY_REMOVE              40363
#define ID_SECURITY_RESET               40364
#define ID_SECURITY_IMPORT              40365
#define ID_SECURITY_EXPORT              40366
#define ID_SECURITY_MOVE_UP             40367
#define ID_SECURITY_MOVE_DOWN           40368
#define ID_SECURITY_POLICY_ACCEPT       40369
#define ID_SECURITY_POLICY_DENY         40370
#define ID_SCHEDULER_ADD                40371
#define ID_SCHEDULER_EDIT               40372
#define ID_SCHEDULER_REMOVE             40373
#define ID_SCHEDULER_REMOVE_ALL         40374
#define ID_SCHEDULER_IMPORT             40375
#define ID_SCHEDULER_EXPORT             40376
#define ID_SCHEDULER_ACTIVATE           40377
#define ID_SCHEDULER_DEACTIVATE         40378
#define ID_SYSTEM_CLEAR                 40380
#define ID_SYSTEM_COPY                  40381
#define ID_SYSTEM_TEST                  40382
#define ID_SYSTEM_TIMESTAMP             40384
#define ID_SYSTEM_VERBOSE               40385
#define ID_SYSTEM_VERBOSE_INFO          40386
#define ID_SYSTEM_VERBOSE_NOTICE        40387
#define ID_SYSTEM_VERBOSE_DEBUG         40388
#define ID_SYSTEM_VERBOSE_WARNING       40389
#define ID_SYSTEM_VERBOSE_ERROR         40390
#define ID_SHELL_MENU                   40392
#define ID_TOOLS_SETTINGS               40400
#define ID_TOOLS_WIZARD                 40401
#define ID_TOOLS_LANGUAGE               40402
#define ID_TOOLS_PROFILE                40403
#define ID_TOOLS_SKIN                   40404
#define ID_TOOLS_RESKIN                 40405
#define ID_TOOLS_SEEDTORRENT            40406
#define ID_TOOLS_RESEEDTORRENT          40407
#define ID_TOOLS_CREATETORRENT          40408
#define ID_TOOLS_DOWNLOAD               40409
#define ID_TRAFFIC_WINDOW               40410
#define ID_TRAFFIC_AXIS                 40411
#define ID_TRAFFIC_CLEAR                40412
#define ID_TRAFFIC_GRID                 40413
#define ID_TRAFFIC_LEGEND               40414
#define ID_TRAFFIC_SETUP                40415
#define ID_TRANSFERS_CHAT               40416
#define ID_TRANSFERS_CONNECT            40417
#define ID_TRANSFERS_DISCONNECT         40418
#define ID_TRANSFERS_FORGET             40419
#define ID_TRAY_OPEN                    40420
#define ID_UPLOADS_START                40421
#define ID_UPLOADS_PRIORITY             40422
#define ID_UPLOADS_LAUNCH               40424
#define ID_UPLOADS_CHAT                 40425
#define ID_UPLOADS_CLEAR                40426
#define ID_UPLOADS_CLEAR_COMPLETED      40427
#define ID_UPLOADS_AUTO_CLEAR           40428
#define ID_UPLOADS_DISCONNECT           40429
#define ID_UPLOADS_FILTER_ALL           40430
#define ID_UPLOADS_FILTER_ACTIVE        40431
#define ID_UPLOADS_FILTER_HISTORY       40432
#define ID_UPLOADS_FILTER_QUEUED        40433
#define ID_UPLOADS_FILTER_TORRENT       40434
#define ID_UPLOADS_FILTER_MENU          40435
#define ID_UPLOADS_FOLDER               40436
#define ID_UPLOADS_LIBRARY              40437
#define ID_UPLOADS_SETTINGS             40438
#define ID_UPLOADS_HELP                 40439
#define ID_VIEW_BASIC                   40440
#define ID_VIEW_TABBED                  40441
#define ID_VIEW_WINDOWED                40442
#define ID_VIEW_DOWNLOADS               40443
#define ID_VIEW_UPLOADS                 40444
#define ID_VIEW_LIBRARY                 40445
#define ID_VIEW_MEDIA                   40446
#define ID_VIEW_NEIGHBOURS              40448
#define ID_VIEW_HOSTS                   40450
#define ID_VIEW_PACKETS                 40451
#define ID_VIEW_DISCOVERY               40452
#define ID_VIEW_RESULTS_MONITOR         40453
#define ID_VIEW_SEARCH_MONITOR          40454
#define ID_VIEW_SECURITY                40455
#define ID_VIEW_SCHEDULER               40456
#define ID_VIEW_SYSTEM                  40457
#define ID_VIEW_TRAFFIC                 40458
#define ID_WINDOW_NAVBAR                40460
#define ID_WINDOW_TOOLBAR               40461
#define ID_WINDOW_TABBAR                40462
#define ID_WINDOW_MONITOR               40463
#define ID_WINDOW_REMOTE                40464
#define ID_WEBSERVICES_LIST             40480
#define ID_WEBSERVICES_MUSICBRAINZ      40481
#define ID_MUSICBRAINZ_MATCHES          40482
#define ID_MUSICBRAINZ_ALBUMS           40483
#define PluginID_Custom                 40500
#define PluginID_ImageViewer_FullSize   40501
#define PluginID_ImageViewer_BestFit    40502
#define PluginID_ImageViewer_Refresh    40503
#define PluginID_ImageViewer_Close      40504

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        381
#define _APS_NEXT_COMMAND_VALUE         40550
#define _APS_NEXT_CONTROL_VALUE         1750
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
