#ifndef MINIUPNPCSTRINGS_H_INCLUDED
#define MINIUPNPCSTRINGS_H_INCLUDED

#define OS_STRING "Envy/1.0.3.0"
#define MINIUPNPC_VERSION_STRING "1.9.20151020"
#define UPNP_VERSION_STRING "UPnP/1.1"

#endif
